### ISSUE TITLE
Change Password cancel button not working

### ISSUE THREAD

**Issue by fabioandreteles** [pwm-project/pwm#113]
Hello. I'm testing the newest versin, after having a March build running smoothly, but where I can't select the minimum lifetime (it only gives me 0-100).  looked for this property on any file, trying to understan if I can change that "error" but without knowing the languages it's very difficult. Could some one guide me on that?

**After trying the latest release on Tomcat8 and Ubuntu 16.04 LTS I was trying the major functions I use, and when I try to cancel the change password action in gives me a blank page or an error**. IT happens on Chrome, Firefox and Opera. On IE everything is OK.

Is something happenging with Tomcat or other problem that I can't understand? The latest version is giving me more trouble than the older one I have. I just needed that function working, minimum password time, and nothing more. Even configuring by hand, option by option, I have more problems now with the newer test version.

Thank you!

**Comment by jrivard** [comment]
Fixed in current master branch.
