### ISSUE TITLE
Wrong page name in ldap-schema.jsp

### ISSUE THREAD

**Issue by Herbis** [pwm-project/pwm#114]
Hi, just noticed the ldap-schema.jsp has incorrect page name on line 41.
`<jsp:param name="pwm.PageName" value="Localization Report"/>`
which instead should probably look like:
`<jsp:param name="pwm.PageName" value="LDAP Schema Definition"/>`

pwm/src/main/webapp/public/reference/ldap-schema.jsp

**Comment by jrivard** [comment]
Fixed in current master branch.
