### ISSUE TITLE
capitalization issue

### ISSUE THREAD

**Issue by x106x** [pwm-project/pwm#116]
Having issues with some users and capitalization when logging in.

When some users log in it seems that they must match capitalization in LDAP before they can properly authenticate.  I had a user try multiple times to log in but only when they tried with proper capitalization (like in LDAP) did it work.

Is this a known issue or possible some LDAP mis/configuration?

**Comment by jrivard** [comment]
please use the pwm-general google group for help questions.

**Comment by x106x** [comment]
There isn't a single mention of capitals/capitalization for usernames.  I will post about it.
