### ISSUE TITLE
using "confirmable" data fields should not renerate extra directory data

### ISSUE THREAD

**Issue by FZachlod** [pwm-project/pwm#118]
When a data field for user registration is added the possibility exists to mark this field to be confirmed.
This leads to another form field turning up where the user has to confirm the original data.

This is widely used with email fields to avoid users putting in email addresses which don't exist.

If this is turned on, a special ldap attribute is being polutated (if possible) in case of email e.g.

"mail_confirm"

For my opinion this does not make sense. The confirmation should take place while the user registers and there is no need for saving both data fields into the directory cause they should always contain the same data. In case a user is being altered later this would lead to the necessity to alter both attributes too.

For my opinion this makes "confirm" useless

**Comment by jrivard** [comment]
confirm form attributes don't save a second value to ldap.  Please ask for help on pwm-general group if your still having trouble.

**Comment by FZachlod** [comment]
It is not true:

Here the log from our directory server:


[14/Mär/2017:15:33:05 +0100] ADD REQ conn=15764 op=5 msgID=6 dn="cn=XXX,ou=cust1-users,dc=test2,dc=XXXX,dc=loc"
[14/Mär/2017:15:33:05 +0100] ADD RES conn=15764 op=5 msgID=6 result=65 message="Entry cn=xxxx,ou=cust1-users,dc=test2,dc=XXXX,dc=loc violates the Directory Server schema configuration because it includes attribute mail_confirm which is not allowed by any of the objectclasses defined in that entry" etime=1

We did not specify mail_confirm anywhere. That happens if we enable [x] confirm for the mail attribute. As soon as we disable it the user can be created. Of course we could add "*_confirm" attributes to out schema but this is just useless.

![2017-03-14 15_38_03-pwmadmin password self service](https://cloud.githubusercontent.com/assets/19568338/23906165/7a94aaf0-08cd-11e7-8bc1-f923cdcf27ae.png)

**Comment by FZachlod** [comment]
[root@pwmtest src]# grep "_confirm" * -R
main/java/password/pwm/util/Validator.java:    public static final String PARAM_CONFIRM_SUFFIX = "_confirm";
main/webapp/WEB-INF/jsp/fragment/form.jsp:    <label for="<%=loopConfiguration.getName()%>_confirm">
main/webapp/WEB-INF/jsp/fragment/form.jsp:    <input style="" id="<%=loopConfiguration.getName()%>_confirm" type="<%=loopConfiguration.getType()%>" class="inputfield"
main/webapp/WEB-INF/jsp/fragment/form.jsp:           name="<%=loopConfiguration.getName()%>_confirm"
main/webapp/WEB-INF/jsp/fragment/form.jsp:                    PWM_MAIN.getObject('<%=loopConfiguration.getName()%>_confirm').value='';

**Comment by FZachlod** [comment]
The web form just creates additional fields with "_confirm" suffix, which are not removed late on. On user creation these are added to the attributes list. I verified this in the code.

Doing this hack:

           if (!formKey.endsWith("_confirm") && value != null && !value.isEmpty()) {
                createAttributes.put(formKey, value);

Enables form verification to work properly without creating _confirm attributes.
