### ISSUE TITLE
Use rest service documentation redirect helper

### ISSUE THREAD

**Issue by 0xdevalias** [pwm-project/pwm#125]
[ws/server/rest/RestCheckPasswordServer.java](https://github.com/pwm-project/pwm/blob/master/src/main/java/password/pwm/ws/server/rest/RestCheckPasswordServer.java#L98-L103) is manually performing the redirect, whereas the other servlets are [using a helper function](https://github.com/pwm-project/pwm/blob/master/src/main/java/password/pwm/ws/server/rest/RestChallengesServer.java#L139-L141)

**Comment by jrivard** [comment]
The REST services have been refactored and no longer redirect to docs.
