### ISSUE TITLE
FOUND A BUG IN PwmValue.java--class ResponseFieldTypeOutput 

### ISSUE THREAD

**Issue by wuhanbin** [pwm-project/pwm#126]
FOUND A BUG IN PwmValue.java--class ResponseFieldTypeOutput
"DISPLAY_MASK_PASSWORD_FIELDS" SHOULD BE "DISPLAY_MASK_RESPONSE_FIELDS"

================================================================================
    static class ResponseFieldTypeOutput implements ValueOutput {
        @Override
        public String valueOutput(final PwmRequest pwmRequest, final PageContext pageContext) throws ChaiUnavailableException, PwmUnrecoverableException {
            final boolean maskPasswordFields = pwmRequest.getConfig().readSettingAsBoolean(PwmSetting.DISPLAY_MASK_PASSWORD_FIELDS);
            return maskPasswordFields ? "password" : "text";
        }
    }

**Comment by jrivard** [comment]
Fixed in latest commit.
