### ISSUE TITLE
some "label" hard-coded in PwmSetting.xml ,cause UI Language can't change absolutely 

### ISSUE THREAD

**Issue by wuhanbin** [pwm-project/pwm#128]
https://***.com/public/forgottenpassword 

In the middle of forgottenpassword page 
Username* 
can't change to other language 

I have to modify PwmSetting.xml , replace "Username" with "用户名" to change UI language 
================================================================================ 
<value>{"name":"sAMAccountName","minimumLength":1,"maximumLength":64,"type":"text","required":true,"confirmationRequired":false,"readonly":false,"labels":{"":"用户名"},"regexErrors":{"":""},"description":{"":""},"selectOptions":{}}</value>

**Comment by jrivard** [comment]
This text can be edited in the config editor by opening the form and clicking on the label value.
