### ISSUE TITLE
malformed urls may bypass LDAP authentication 

### ISSUE THREAD

**Issue by pizzarabe** [pwm-project/pwm#129]
We are not sure if this is a problem or not but:

You can bypass the /public/ForgottenPassword page (skipping the LDAP auth) by changing the url to sth. like 
`"https://[servername]/public/ForgottenPassword;sometext"`.
 The Server redirects to the sms token input page
`"ForgottenPassword?processAction=enterCode&token=%3B<sometext>pwmFormID=<formid>"`.

The server definitive does sth. (right now we still investigating if the server sends an sms) but we were not able to do some codeinjection or sth. like that. 

Maybe this is nothing serious but we don't now for sure :)

**Comment by jrivard** [comment]
This is working as designed.  This is the URL sent to user to click on.  The scenario you discovered is for when the user clicks the email in some cases the link will not open in an existing SSPR session - either it will use a different browser or the SSPR session will have timed out.  In this case the token is used as an identifier and the user is re-verified according to the configuration settings.
