### ISSUE TITLE
'reference/settings.jsp' probably shouldn't be publicly accessible

### ISSUE THREAD

**Issue by alias1** [pwm-project/pwm#131]
https://example.com/cas/pwm/public/reference/settings.jsp

While care has been taken to remove a number of sensitive details, this still provides an attacker with a large amount of information that they could use to better target their attack.

If this page remains as is, care should be taken to treat a lot more of the fields as sensitive, including:
* `captcha.skip.param`
* `captcha.skip.cookie`
* `db.url`
* `email.smtp.address`
* `email.smtp.username`
* `https.server.cert`
* `intruder.user.resetTime`
* `intruder.user.maxAttempts`
* `intruder.user.checkTime`
* `intruder.attribute.resetTime`
* `intruder.attribute.maxAttempts`
* etc intruder values
* `events.java.log4jconfigFile`
* `sms.gatewayUser`
* `disallowedInputs`
* `useXForwardedForHeader`
* `network.requiredHttpHeaders`
* `network.ip.permittedRange`

And probably others (this was just from a quick skim over the page). As you can see, there's a lot of information there that could potentially be used to aid an attack.

**Comment by jrivard** [comment]
Seriously?

**Comment by alias1** [comment]
Given you've closed the issue you clearly don't think it's valid.. but could you please explain why you think so?

**Comment by jrivard** [comment]
This is a publicly accessible reference documentation.  There is no secret information in that document.

**Comment by alias1** [comment]
In viewing it, it appeared to me to be reflecting the values configured in the actual settings file (with some values such as passwords hidden) Is that not the case? If it is just static reference docs then forgive my mistake and I withdraw my issue. (will confirm against the source when I get back on a real computer)
