### ISSUE TITLE
Password change page resets on submit

### ISSUE THREAD

**Issue by dezdez** [pwm-project/pwm#132]
In pwm-1.8.0-SNAPSHOT-2017-01-24T23:03:50Z, when a user attempts to change their password, the password change page simply resets.

The following events are logged when this occurs.

`
2017-02-09T03:18:42Z, DEBUG, servlet.AbstractPwmServlet, {20,dstest2} this request is not idempotent, redirecting to self with no action [10.11.10.58]

2017-02-09T03:18:42Z, TRACE, http.PwmRequest, {20,dstest2} POST request for: /pwm/private/changepassword [10.11.10.58]
  processAction='change'
  password2=*hidden*
  password1=*hidden*
` 

The message regarding the request not being idempotent was added to the source code last month. So I am assuming that this issue was introduced then.

Please let me know what further information I can supply to assist with troubleshooting this? Also, in the meantime, would you advise me to install an earlier version instead?

Thanks.

**Comment by dezdez** [comment]
I am using Active Directory & running PWM on Windows.

**Comment by dezdez** [comment]
This occurs under Tomcat 7 & Tomcat 8

**Comment by dezdez** [comment]
After trying various versions I managed to get v1.7.1 working. This appears to be able to change passwords without any problems.

**Comment by jryberg** [comment]
I have the same issue, it's kind of a show stopper. Unfortunately I'm not able to commit a fix for this since this is outside my skill set.

**Comment by jrivard** [comment]
Fixed in latest commit.
