### ISSUE TITLE
Allow authentication when "must change password...." not working

### ISSUE THREAD

**Issue by roycamp** [pwm-project/pwm#133]
Allow authentication when "must change password on next login" is not working.  When I set that flag on a user and try to login, it just says wrong username/password. 
I have not been able to get this to work despite disabling and re-enabling the setting.  I have also tried disabling the "use proxy when password forgotten" setting.  It is possible I have a permission issue in AD (perhaps the proxy account not having enough permission?). Any ideas? Thanks

**Comment by jrivard** [comment]
Please ask for help on the google groups
