### ISSUE TITLE
5083 ERROR_ENVIRONMENT_ERROR (application path is not specified)

### ISSUE THREAD

**Issue by designateddesigner** [pwm-project/pwm#139]
Forgive me, I am a complete noob when it comes to serving web apps with Java. After some research into using Tomcat, I first stopped the service and placed the pwm .war file into /var/lib/tomcat7/webapps and then started Tomcat back up. I then visited ser.ver.ip.adr:8080/pwm and found this '5083' error and could not find any information on Github or the Google Group about it. I clicked on the "Environment Configuration Reference" link and it displayed a page with this message:

**error reference 6FD2FF87CF2FFCBEB7B5A9BFB17393011FF76A0A**

Where did I go wrong? Should I use a reverse proxy such as nginx if I'm going to use pwm outside of localhost?

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
