### ISSUE TITLE
Blank page occurs when a new password is rejected by LDAP

### ISSUE THREAD

**Issue by sntr8** [pwm-project/pwm#140]
PWM uses local password policy but LDAP enforces requirement for using a new password instead of using one used in the past. 

When user tries to change his/her password to a previously used one, PWM accepts the password but after getting error javax.naming.directory.InvalidAttributeValueException (LDAP error code 19) from LDAP, it redirects user to /pwm/private/changepassword displaying a blank page without any errors.

**Comment by sntr8** [comment]
This has been working prior to commit 7a1a971. The page tries to redirect user to resources/dojo but can't found anything as files are moved under resources/webjars/dojo

**Comment by subst4nc3** [comment]
same problem here... blank page after the user tries to change the password that violate AD rules (minimum password age)

**Comment by jryberg** [comment]
Is there any manual work around available?

**Comment by sntr8** [comment]
We are using PWM as it was in commit 2e3a819. It does work fairly good when you include fix made in commit abf5607 manually.

**Comment by jrivard** [comment]
Fixed in latest commit.
