### ISSUE TITLE
Username is statcally in English on user search page

### ISSUE THREAD

**Issue by sntr8** [pwm-project/pwm#141]
Username disregards selected locale on user search page during change password and forgotten password wizards.
<img width="652" alt="screen shot 2017-02-28 at 15 58 38" src="https://cloud.githubusercontent.com/assets/25769156/23408040/3d5d104a-fdcf-11e6-8727-620c4d7c75cd.png">
<img width="627" alt="screen shot 2017-02-28 at 15 58 43" src="https://cloud.githubusercontent.com/assets/25769156/23408038/3d57ee9e-fdcf-11e6-8101-7e1a3486dfcb.png">
<img width="640" alt="screen shot 2017-02-28 at 15 58 49" src="https://cloud.githubusercontent.com/assets/25769156/23408039/3d5af512-fdcf-11e6-848c-d690b30564d4.png">

**Comment by jrivard** [comment]
Edit the label for the forgotten password search form
