### ISSUE TITLE
Locale flags missing after commit 7a1a971

### ISSUE THREAD

**Issue by sntr8** [pwm-project/pwm#142]
Locale flags are missing in dijit popup frame. Flags, however, are visible at the bottom of the page.

In popup PWM tries to load icons from /pwm/public/resources/flags/png/xy.png and at main page it will load them from /pwm/public/resources/webjars/famfamfam-flags/dist/pnf/xy.png. 

<img width="546" alt="screen shot 2017-02-28 at 15 59 12" src="https://cloud.githubusercontent.com/assets/25769156/23408261/1bb8fcfa-fdd0-11e6-810f-e475f7f3bba8.png">

**Comment by sntr8** [comment]
As a workaround until a fix is implemented, flags can be added manually to the PWM war. 
- Extraxt famfamfam-flags-1.0.0.jar located in pwm/target/pwm-1.8.0-SNAPSHOT/WEB-INF/lib
- Copy relevant png files from META-INF/resources/webjars/famfamfam-flags/1.0.0/dist/png to pwm/src/main/webapp/public/resources/flags/png directory (needs to be created)
- Package war

**Comment by jrivard** [comment]
Fixed in latest commit.
