### ISSUE TITLE
PWM does not search people with UTF-8 (Russian)

### ISSUE THREAD

**Issue by tatarenko** [pwm-project/pwm#152]
PWM version: Last snapshot
People Search module perfectly search on English:
![image](https://cloud.githubusercontent.com/assets/4854544/24064481/bfa5752a-0b75-11e7-982d-8d40de6475bb.png)
But having problem with UTF-8:
![image](https://cloud.githubusercontent.com/assets/4854544/24064496/dbd8b6bc-0b75-11e7-96a4-dd1b4120846b.png)
Even though person is in directory
![image](https://cloud.githubusercontent.com/assets/4854544/24064512/f6e57562-0b75-11e7-839a-a965c213951c.png)
Same search perfectly fine on Helpdesk module:
![image](https://cloud.githubusercontent.com/assets/4854544/24064544/1253d01e-0b76-11e7-8f3d-235f310289df.png)

**Comment by jrivard** [comment]
I believe this is fixed in current builds.
