### ISSUE TITLE
Unable to change challenge response if initial entry is too short.

### ISSUE THREAD

**Issue by mdiorio** [pwm-project/pwm#157]
When a user registering enters a challenge question password that is too short, there is no option to return to the previous screen to fix it.  They get prompted with:
```
PWM 5008
The response for question "What is your favorite team?" is too short
```
And there is no way to resolve this.  If they try to log in again, it immediately bring them back to this screen.

**Comment by jrivard** [comment]
This issue was fixed in the most recent update.
