### ISSUE TITLE
Administrator Group doesn't allow nested groups

### ISSUE THREAD

**Issue by chanster** [pwm-project/pwm#16]
When adding a LDAP Group for administration, it does not detect users if they are nested within another group.

**Comment by jrivard** [comment]
Probably won't ever happen.  The group permission just looks on the user object for a direct reference to the group.  If this isn't there then PWM won't see the group.  It depends on your LDAP implementation whether this happens naturally in LDAP for a nested or other types of group.  You can try to use a filter instead.
