### ISSUE TITLE
PWM not honoring: 'Minimum Random Required'

### ISSUE THREAD

**Issue by itwizzy** [pwm-project/pwm#164]
Hello,

I have changed this to 3 however PWM is only asking for 2.

The total number of answers users must provide is 5. So don't really know whats going on here. 

Cheers

**Comment by itwizzy** [comment]
<setting key="challenge.minRandomRequired" syntax="NUMERIC" profile="default" syntaxVersion="0" modifyTime="2017-04-12T06:42:31Z" modifyUser="default|CN=AdminWAmmoun,OU=Administrator Accounts,OU=Hollard,DC=Hollard,DC=Group">
      <label>Minimum Random Required</label>
      <value>3</value>
    </setting>
    <setting key="challenge.minRandomsSetup" syntax="NUMERIC" profile="default" syntaxVersion="0" modifyTime="2017-04-12T06:46:17Z" modifyUser="default|CN=AdminWAmmoun,OU=Administrator Accounts,OU=Hollard,DC=Hollard,DC=Group">
      <label>Minimum Random Challenges Required During Setup</label>
      <value>5</value>
    </setting>

**Comment by itwizzy** [comment]
<label>Minimum Random Challenges Required During Setup</label>
      <value>5</value>

**Comment by jrivard** [comment]
Please ask for assistance on the pwm-general group.
