### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by alerque** [pwm-project/pwm#166]
I'm manage the Arch Linux packages for this project. It's very hard to maintain good distro packages without  tagged release points. Kindly please tag the git commits corresponding to released versions.

**Comment by lorengordon** [comment]
👍 yes, please, this would be great.

**Comment by jrivard** [comment]
We don't have any releases in git, so there's nothing to tag....

**Comment by alerque** [comment]
See also #510. This is _still_ an issue.

@jalbr74 You have an internal version number that keeps changing. Git tags should reflect where those versions change.
