### ISSUE TITLE
Korean language mixed in Thai translation

### ISSUE THREAD

**Issue by weeix** [pwm-project/pwm#169]
Hi,

In Thai translation, I found some message that is written in Korean. For example:

In [Error_th.properties](https://github.com/pwm-project/pwm/blob/master/src/main/resources/password/pwm/i18n/Error_th.properties) line 112, when converted unicode to characters:

> Password_NotEnoughUpper=새 암호에 충분한 수의 대문자가 없습니다

I'm Thai. May I help with the translation?

**Comment by jrivard** [comment]
Please submit a pull request.
