### ISSUE TITLE
"out of order page request" bug in Help Desk password reset

### ISSUE THREAD

**Issue by ducasi** [pwm-project/pwm#176]
v1.8.0-SNAPSHOT b24942858 r6dfa0ebc06b6072dac9bd5a675f2c932bce64ed8

(Snapshot build from 8th May 2017.)

When I use the Help Desk module to reset a user's password, when I click the "OK" button on the confirm dialog box, I get this error:

Error 5035
An out of order page request has been received. Please do not use the browser back button. Please try again.

If I click the close button on the dialog, the error does not appear.

**Comment by jrivard** [comment]
I believe this is fixed in current builds.
