### ISSUE TITLE
Upgraded and pwm sort of broke 

### ISSUE THREAD

**Issue by jcroy** [pwm-project/pwm#179]
We use pwm for our website to allow customers to reset their passwords.  We upgraded ubuntu and openldap and now I've been told that pwm is buggy.  It still resets passwords and allows you to set a password but it does not honor the change and instead changes it to something random.  Any ideas what might cause the issue? Ive been asked to figure out the cause of this.  The error code we are getting is PWM 5033 followed by The configuration is invalid or corrupt. Please correct the error, or remove the configuration file.

**Comment by jrivard** [comment]
please ask for help on the pwm-general google group
