### ISSUE TITLE
Error 5035 with the Help Desk module

### ISSUE THREAD

**Issue by stefanotoro** [pwm-project/pwm#182]
**Build** pwm-1.8.0-SNAPSHOT-2017-05-24T20-19-32Z-pwm-bundle

**Step to reproduce** 

1. Sign in with a user with permissions, go to Help Desk module
2. Find a user and Change is Password
3. Type a new password and click "Change Password".
4. The message "The password has been changed successfully" appears. Click "OK"
4. Error 5035 with the message "An out of order page request has been received. Please do not use the browser back button. Please try again." Click "OK"

But the password as been changed for the user and after you click OK the page reload to the result of the step 2.

Thank you

**Comment by yanncam** [comment]
Hello @stefanotoro,

I had the same error until this commit : https://github.com/pwm-project/pwm/commit/9efc6d73b1d7288177ab0d9e5e4a6f2a4ded842b

If you deploy the latest built, it seems to be fixed.

Sincerely,

**Comment by stefanotoro** [comment]
Hello,

Thank you! I will try it the next week.

Best regards
Stefano

**Comment by stefanotoro** [comment]
Bug fixed !
Thank you
