### ISSUE TITLE
PWM Action type: java

### ISSUE THREAD

**Issue by Futvin** [pwm-project/pwm#187]
Hello, I hope this is the correct way to suggest features to the PWM project.

I make some minor changes to the PWM so that you could specify a java class as an action time.  Of course, the java class has to be in the class path underneath the hood.  I am sure there are some edge cases which I did not test for, but this code works fine in our build of the PWM.

I created these changes with a build from January (I believe).  So I merged my changes in with the current snapshot build, and checked them into this fork: https://github.com/Futvin/pwm.

Does that work for you?

Cheers,
Aaron

**Comment by demesg** [comment]
Aaron, 
This is exactly the function I wish in PWM, hope it is accepted and merged with the master.
Regards Magnus

**Comment by jrivard** [comment]
I don't think this is a great idea, you could easily implement a REST interface just as easy or easier then java interface.  In any case, if there is a pull request we'll evaluate it.
