### ISSUE TITLE
Reset password page generates "Please match the requested format" on any text input (Chrome & Safari)

### ISSUE THREAD

**Issue by nielsen-at-cgt** [pwm-project/pwm#204]
With Chrome and Safari (yet not Microsoft Edge), the reset password page generates the display "Please match the requested format" for any entered text.  The user cannot proceed past that point.

The following message appears in the Safari console; I don't know if it is related:

- __Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.__

**Comment by nixmomo** [comment]
Thats not a pwm error... Its a error in your webservers config...Script Security Header is thats for what you should looking for in your config
