### ISSUE TITLE
Building project with maven and prebuilt .war files are broken.

### ISSUE THREAD

**Issue by MaRRiK74** [pwm-project/pwm#226]
I have tried all options but it seems that 'all' prebuilt images are broken, I have tried several. Building with maven doesn't seem to work either. Tried multiple maven version on Ubuntu and Windows.

**Comment by jrivard** [comment]
I downloaded 'pwm-1.8.0-SNAPSHOT-2017-09-13T17:23:36Z-release-bundle.zip' and was able to deploy the pwm.war without issue.  I also did the following:

git clone https://github.com/pwm-project/
cd pwm
mvn pacakge

and the resulting war in server/target was able to deploy just fine.
