### ISSUE TITLE
Smart Card Auth

### ISSUE THREAD

**Issue by brywil** [pwm-project/pwm#227]
Have you ever considered smart card authentication for the front-end?  If nothing else, this would be a secure way to authenticate administrators, but this would solve a huge problem for our environment.  All of our users have smart cards with SSL client certs, but we have some applications which only work with username and password.  We have a policy which forces users to reset passwords every 90 days so we spend a significant amount of time resetting user passwords.  The reset questions help, but some of our users don't feel that reset questions are secure enough.  Frankly, I'm surprised that our security office permits their use.  If our users could log in to the password manager with SSL client certificates, you would greatly simplify our lives.  

I would even be willing to take a stab at a patch if you're willing to work with me.  I don't have time to maintain my own fork of the pwm-project, but would be happy to contribute this feature to the project!

**Comment by jcombs-pointblue** [comment]
This is already available by integrating with existing strong authentication products such as NetIQ Advanced Authentication and NetIQ Access Manager. Using Access Manager you could eliminate the need for people to know passwords for the password dependent apps.

Adding simple certificate validation to PWM would not be too difficult but it would be much more limited than what you get with the commercial products.
