### ISSUE TITLE
Adding new users to groups

### ISSUE THREAD

**Issue by muppeth** [pwm-project/pwm#23]
Is it possible to add new users to groups?
I'm trying to find out how I could add a value to attribute in different entry than the currently created user entry.

For example, PWM creates user in `uid=tester,ou=people,dc=example,dc=com` and I would like to add a value (user uid) to `memberUid: cn=user,ou=groups,dc=example,dc=com`. Is this possible?

**Comment by jrivard** [comment]
Discussions belong on the pwm-general google group.
