### ISSUE TITLE
PWM 5027 error when accessing Configuration Editor in IE 11

### ISSUE THREAD

**Issue by dcozzy** [pwm-project/pwm#235]
Build:
PWM 1.8.0 (2017-09-25T10_18_28Z
Tomcat 8.5.20

Admin account with proper permissions can access Configuration Editor from within Firefox, but not from IE 11, or Chrome 62.0.3202.75. Throws PWM 5027 error. "You do not have permission to perform the requested action." Tomcat or PWM version to blame? Thoughts?

**Comment by rkeil-git** [comment]
I updated to the Chrome 62.0.3202.75 and logged in in IE 11 and they were both able to go to the configuration editor. I was able to make changes in IE and they appeared in Chrome.

Richard

**Comment by dcozzy** [comment]
Thank you Richard for this expeditious response.
Guess my company browser policies are preventing the action to perform. Any suggestions on what needs to be enabled in the browser(s) to accomplish this?

Thanks,
David

**Comment by rkeil-git** [comment]
If you could send me a lan trace or a support bundle I could look at the log files to see what request is being made and what the error is that we are returning.

Richard

**Comment by dcozzy** [comment]
Richard,
I ran an netsh trace – the output is attached.
does this work for you?

David

**Comment by rkeil-git** [comment]
David,

Our email system did not let the attachment come through. Is there any other way I can get the netsh trace??

Richard

**Comment by dcozzy** [comment]
Hello Richard,
I’ve zipped it down to a mere 1MB. I’ll see if I can reduce it further, or break into smaller files.
Thanks,
David

Sent from my iPhone

On Nov 2, 2017, at 6:15 PM, rkeil-git <notifications@github.com<mailto:notifications@github.com>> wrote:

David,

Our email system did not let the attachment come through. Is there any other way I can get the netsh trace??

Richard

**Comment by rkeil-git** [comment]
David

I don't know why but it will not let it through. Is there a different way I can get it?

Richard
________________________________

**Comment by dcozzy** [comment]
Richard –
I’ll send you an invite to dropbox

David

**Comment by dcozzy** [comment]
Hello Richard,
Any luck accessing the trace?

David

From: David Cozzy
Sent: Friday, November 03, 2017 8:27 AM
To: pwm-project/pwm <reply@reply.github.com>; pwm-project/pwm <pwm@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [pwm-project/pwm] PWM 5027 error when accessing Configuration Editor in IE 11 (#235)

Richard –
I’ll send you an invite to dropbox

David

**Comment by rkeil-git** [comment]
David,

I have read it but I don't see any useful information. I was looking for a LAN trace that show me the rest requests and the replied so I could try an identify why the error was being returned. I have not been able to find that information is the trace that I accessed. It appears to be a windows event trace. I will see if I can find anything else.

Richard
________________________________

**Comment by dcozzy** [comment]
Hi Richard –

I’ve run a Fiddler trace and have saved the output (pwm.saz) in the dropbox. I hope this is data you can use.
Line 143 is where I make to attempt into the configuration editor and am presented with the 5027 error.

Thanks in advance,
David

**Comment by rkeil-git** [comment]
David,

When I look through the trace I don’t see an error on entry 143 but I see that error you are reporting on entry 142. It indicates that you do not have permission. Are you logging in as the same person when you use Firefox as when you use IW or chrome.  Is the person you are logging in as in the admin group or did you give them rights as an individual?

The place where the error that is returned in the trace is where a check in made for permission is checked to see if you are in the admin group.

I don’t see any other way that the error indicating that you don’t have permission is returned.

Sorry I don’t see more.

Richard

**Comment by dcozzy** [comment]
Hello Richard,
Yes, using the same account. User is in the pwm admin group.

Thanks for looking,
David

**Comment by jrivard** [comment]
The browser user-agent detection library has been updated in the current pwm releases.   Please re-open if this problem still occurs.
