### ISSUE TITLE
Ping UnboundID password expiration time attribute unrecognized by PWM 

### ISSUE THREAD

**Issue by dcozzy** [pwm-project/pwm#237]
Assuming passwordExpirationTime attribute is the correct attribute to use for password expiration sync. Ping UnboundID does not have such an attribute, and although after creating one specific for the operation, PWM does not recognize the attribute. 
Is the attribute PWM expecting for password expiration, passwordExpirationTime?
Attribute name=passwordExpirationTime
Multivalued=no
Syntax= Generalized Time
If other attribute is required, please identify. 
Thank you.

**Comment by jrivard** [comment]
pwm doesnt have support for unboundID

**Comment by uptown2** [comment]
Can you provide any more information on why UnboundID isn't supported.  With more information maybe we could find a way to make it work.
