### ISSUE TITLE
pwmEventLog

### ISSUE THREAD

**Issue by schwoerb** [pwm-project/pwm#24]
I am seeing issues with the pwmEventLog attribute and password changes. It is further encapsulating attributes on each password change.

\<?xml version="1.0" encoding="UTF-8"?>
\<history>
\<record timestamp="1447104811603" eventCode="EventLog_ChangePassword" srcIP="[Attribute: srcIP=&quot;[Attribute: srcIP=&quot;IPV4addr&quot;]&quot;]" srcHost="[Attribute: srcHost=&quot;[Attribute: srcHost=&quot;FQDN&quot;]&quot;]" />
\<record timestamp="1447173195228" eventCode="EventLog_ChangePassword" srcIP="[Attribute: srcIP=&quot;IPV4addr&quot;]" srcHost="[Attribute: srcHost=&quot;FQDN&quot;]" />
\<record timestamp="1447175527107" eventCode="EventLog_ChangePassword" srcIP="IPV4addr" srcHost="FQDN" />
\</history> 

As far as I can tell it is because in LdapXmlUserHistory.java  fromXML that 
final String srcAddr = hrElement.getAttribute(XML_ATTR_SRC_IP) != null ? hrElement.getAttribute(XML_ATTR_SRC_IP).toString() : "";
final String srcHost = hrElement.getAttribute(XML_ATTR_SRC_HOST) != null ? hrElement.getAttribute(XML_ATTR_SRC_HOST).toString() : "";

instead of:
final String srcAddr = hrElement.getAttribute(XML_ATTR_SRC_IP) != null ? hrElement.getAttribute(XML_ATTR_SRC_IP).getValue() : "";
final String srcHost = hrElement.getAttribute(XML_ATTR_SRC_HOST) != null ? hrElement.getAttribute(XML_ATTR_SRC_HOST).getValue() : "";

**Comment by jrivard** [comment]
fixed in commit 139076c
