### ISSUE TITLE
PWM Update Details Issue

### ISSUE THREAD

**Issue by duriesol** [pwm-project/pwm#243]
Hi There

I have started using SSPR/PWM and this is my first time submitting a new issue on this forum. Please let me know if there is a specific process on how to this done in the future.

Before I describe my issue this is the build I have currently installed.
“build_Time":"2017-10-30T21:53:29Z”
"build_JavaVersion":"1.8.0_131”
"build_Version":"1.8.0-SNAPSHOT”

I have installed and tested with the latest build released 19/11/2017 and the same problem persists.

The problem is that after I have logged onto the app and try to update my alternate email address, the notification email is sent to the old address and not the new updated address, I assume this is a bug in the app that you may need to look at.

Awaiting your feedback in anticipation!!!
Durie

**Comment by duriesol** [comment]
Is there anyone on this forum that can shed some light?

**Comment by jrivard** [comment]
This isn't a forum.  Please ask for help on the pwm-general discussion forum.
