### ISSUE TITLE
"Allow Numeric Characters" setting leads to "New password has too many numbers."

### ISSUE THREAD

**Issue by dwhagar** [pwm-project/pwm#247]
So, the system seems to think that when I check the box to enable "Allow Numeric Characters", when I attempt to do a new user, I get the message "New password has too many numbers." if there are any numbers.  I've checked the configuration XML and it is set to "true" in there as well, to allow numeric characters.

The password policy text even reflects this, saying that it "Must not include any numeric characters."  The same is true for the other character types, even if I specify in the configuration that I want to enforce AD 2008 rules (which is what I'd like to do), it does not change this.  The only acceptable password is a simple alphabetic password.  With the AD 2008 rules enforced, literally no password is acceptable.

I then tried to reverse the settings, thinking that there was some logic error at play.  however, this wasn't true either, I'm really at a loss.  I had an adjacent problem with an older version of PWM, where it would reverse the text, but not the functionality.  So it would SAY that it must not contain numbers, but it actually wanted it.  This, seems to reverse both, and for the life of me, I cannot figure out why.

**Comment by mijutu** [comment]
I have the same problem. 
`<setting key="password.policy.allowNumeric" …> …
<value>true</value>`

but still can't have numbers in passwords.

**Comment by mijutu** [comment]
And the same problem with allowSpecials. I got numbers and specials accepted by forcing them on in PwmPasswordRuleValidator.java

**Comment by jrivard** [comment]
please ask for help on the pwm-general list.
