### ISSUE TITLE
Unify Security Questions

### ISSUE THREAD

**Issue by frgomjur** [pwm-project/pwm#254]
I have configured the self service module with the Security questions, and also the help desk Module. The problem is that in order to the users can auto-reset their password, or the help desk can do it too, the users need to complete two sets of questions, and that is a bit nigmare for them. Is it possible to unify both sets of verification questions in only one set that the user should fill?. This set of questions would be use either for user auto-reset, or for a technician in the help desk to identify the user, in case of a user call them.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general mailing list.  I'm not sure what your asking for.  If your asking if the same challenge/responses can be used for forgotten password and helpdesk then the answer is no.  The forgotten password responses are one-way hashed and the helpdesk questions are not, so they can't both be used for both purporses.
