### ISSUE TITLE
Can't add a custom theme

### ISSUE THREAD

**Issue by szanellato93** [pwm-project/pwm#255]
Hi to everyone. I'm trying to add a custom theme to the theme list. I upload the zip file themes like in this video:

https://www.youtube.com/watch?v=bqX-ymk_8ZU

but when i select the custom theme nothing happen. Also selecting embedding option and adding the class to embedded css section, all work fine. I'm missing something? Thank you

**Comment by jrivard** [comment]
Please ask for help on the pwm-general discussion forum.
