### ISSUE TITLE
Error 5015 Upon Login/Setup

### ISSUE THREAD

**Issue by JYanez97** [pwm-project/pwm#275]
We recently started trying to set PWM up in our district but are running into issues. The main issue we are getting is error 5015.

> Error 5015
> An error has occurred. If this error occurs repeatedly please contact your help desk.
> 
> 5015 ERROR_UNKNOWN (unexpected error during ldap search (profile=default), error: 5015 ERROR_UNKNOWN (ldap error during searchID=1, error=javax.naming.PartialResultException, cause:javax.naming.CommunicationException: ourdomain.org:636, cause:java.net.ConnectException: Connection timed out: connect))

This does not always happen immediately though. It mainly happens when a user tries to login a few minutes after the server is first configured. It allows me and others to connect to our Microsoft AD server the first 30 minutes and then we all get prompted with Error 5015 upon login. Eventually, it will let us login back in but it takes up to an hour. 

I have tried redoing PWM multiple times but we always end up back at 5015. Sometimes I cannot even get passed adding the domain group for PWM admins. Half the time it works fine and I can see the users in the group. Others it will give the Error 5015 when I try and look at the users in the group before hitting next but I still get the green light because the group DN is correct. Today I also ran into the issue of it did not immediate timeout during setup but I showed 0 users in the group even though there are two users in it.

We are trying to get this running on a Windows Server 2016 Standard server. Our schema has been expanded properly and the permissions for users to use them. The version we are using is "PWM v1.8.0-SNAPSHOT b31814690 rdeca9b1e3a39f38ba6213c6f340b9983cc975516" 

Any help would be greatly appreciated. Thank you in advance!

**Comment by jcombs-pointblue** [comment]
The forums are the right place to ask about this…

But, I assume you are using AD as this issues is common there. What is happening is your search is returning an LDAP referral. The client is then trying to connect to the server in the referral but that connection is failing. Try setting your search bas to a lower level in the tree if possible.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general forums.
