### ISSUE TITLE
message undefined when theme selected

### ISSUE THREAD

**Issue by giorgiocanale** [pwm-project/pwm#28]
Hi, when using a theme different from custom or default (those are basically empty so only the general one is applied) if I entera wrong username and/or password i get a box on the login page alertin me about "Password or username not valid". After some moments, selecting the tho inputbox, in the box with error message is appended some html code like "<div class="message undefined" ..."
It seems that having to process 2 stylesheet something goes wrong on the javascript that handle that messagebox

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
