### ISSUE TITLE
SNI support for TLS client

### ISSUE THREAD

**Issue by fwi27** [pwm-project/pwm#30]
PWM does not support SNI when establishing TLS connection, for instance when calling a SMS HTTPS API which have multiple certificates on the same IP address.
It seems the problem relies on the outdated version of Apache httpclient used by PWM. Version 4.2.2 is used, only version 4.3.2 and later supports SNI : https://issues.apache.org/jira/browse/HTTPCLIENT-1119

There is currently a bug related to SNI in Java 8  when custom HostnameVerifier is used, I don't know if solving the SNI problem for PWM may be impacted : https://bugs.openjdk.java.net/browse/JDK-8144566

**Comment by jrivard** [comment]
Current build has updated httpclient, please rested and reopen if this is still an issue.
