### ISSUE TITLE
Unable to answer security questions

### ISSUE THREAD

**Issue by sduensin** [pwm-project/pwm#338]
Short of entering random gibberish, I almost always get the error “your answer to [question] is too commonly used” when trying to fill out the security questions for account recovery.

Can I just tell PWM that I don't care how common answers are?

**Comment by RobBridgeman** [comment]
During the initial configuration, you can set "Apply wordlist" on the security questions.

If you already have an account which has been setup, you can use the admin password to get into the configuration manager.(Login > Administration > More Options > Configuration Editor) From there, you can go Policies > Challenge Policies > Default. Here you can change the security questions and disable "Apply wordlist".

**Comment by sduensin** [comment]
Ah!  I looked all over for that and hadn't found it.  Thank you!
