### ISSUE TITLE
Self Service Password reset for Windows OS[windows Server 2012 R2]

### ISSUE THREAD

**Issue by AllenWu2k** [pwm-project/pwm#368]
Hello, everyone, The following error occurred in the deployment of Self Service Password reset reset **PWM Configuration Guide**, In the Administrators Group step,  the following error occurred 
![image](https://user-images.githubusercontent.com/38985030/39635470-33a26d56-4ff0-11e8-8857-eb8bd53d6c09.png)
but I have created the group in the active directory, as shown in the following figure
![image](https://user-images.githubusercontent.com/38985030/39635483-3b67e412-4ff0-11e8-8aa2-77d918733823.png)
Re-installed, the problem is the same, how to solve, thank you!

**Comment by geekmichael** [comment]
Can you try with the **Browse** button?  Just make sure the group DN is correct.

**Comment by facundeichon** [comment]
You have to put an Admin Group DN, not just a simple user.

**Comment by sriramsundarsm** [comment]
Can someone help me for Certificate installation for Active directory 2012.

**Comment by jrivard** [comment]
Please ask for help in the pwm-general google group.
