### ISSUE TITLE
error translating ADDB to PwmSettingTemplate

### ISSUE THREAD

**Issue by ImNtReal** [pwm-project/pwm#38]
Since a recent upgrade from 1.7 to the most recent 1.8 snapshot, my system log is filling with:
WARN , util.Helper, unexpected error translating input=ADDB to enumClass=PwmSettingTemplate.

Is ADDB an old config value that should be updated?

**Comment by jrivard** [comment]
Yes, change the ldap vendor template setting, it's the first option on first page of the configeditor.
