### ISSUE TITLE
pwm v1.7.1, forgot password and recaptcha v1 shutdown

### ISSUE THREAD

**Issue by mshlearns** [pwm-project/pwm#381]
We have pwm v1.7.1 from past few years and suddenly the forgot password is not working. It just show the loading icon and doesn't show the recaptcha. When investigated found that pwm v1.7.1 uses recaptcha v1 which has shutdown in Mar 2018.

I registered for recaptcha v2 and updated the configuration xml with new public and private keys, but still the recaptcha is not showing up.

Does the pwm v1.7.1 requires code changes to upgrade recaptcha to v2 ?
How can we upgrade to recaptcha version 2 without upgrading the pwm version?

**Comment by mshlearns** [comment]
Can somebody help me please?

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.  This issue tracker is for bug reports.
