### ISSUE TITLE
Cannot change Password if user is locked out

### ISSUE THREAD

**Issue by subst4nc3** [pwm-project/pwm#394]
the issue is described here:
https://groups.google.com/forum/#!topic/pwm-general/N-tRF3Uzxas

**Comment by jrivard** [comment]
Merged fix.  Note this issue only seems to occur when running on tomcat 7.  Tomcat 8.5+ are unaffected.

**Comment by subst4nc3** [comment]
Hello,
Just to try i have installed tomcat 8.5.32 on a centos 7 distro.
I confirm that with that version boolean or Boolean seems that do not
matter, but...
I'm still unable to reset the password if the account is locked out... the
corresponding button on the choice page is greyed out.
So same behaviour that occurs on tomcat 7.x
Regards
GM

Il mar 7 ago 2018, 20:06 Jason Rivard <notifications@github.com> ha scritto:
