### ISSUE TITLE
Feature Request: Add option to 'Use Proxy Connection' within the Setup Security Questions module.

### ISSUE THREAD

**Issue by ewierschke** [pwm-project/pwm#402]
Would like to request an option to 'User Proxy Connection' (or similar) be added to the Setup Security Questions module so that the proxy user is used instead of the logged in user to store the security question responses.

Our use case allows users to create their own initial user account but then as soon as the account is created using the New User Registration module's 'New User Actions', the account is immediately disabled by setting the userAccountControl AD attribute (to later be enabled after verification).  We want to require users to setup their security questions to increase use of the password recovery feature so 'Force Response Setup' is configured in Setup Security Questions however, since new accounts are immediately disabled by our new user action, new users are taken to setup their security questions after account creation but are not able to submit/save them.  If it is possible to have an option for the proxy user to save the security question responses this would help our use case.
Thanks.

**Comment by lorengordon** [comment]
Hi @jrivard, was this closed because it was implemented at some point?
