### ISSUE TITLE
Feature Request: Adjust/validate configuration from command line

### ISSUE THREAD

**Issue by philomory** [pwm-project/pwm#423]
As a sysadmin, I want to manage PWM with a Configuration Management tool such as Puppet. Normally, I'd just have Puppet create PwmConfiguration.xml from a template, filling in values based on data stored on the puppetmaster. However, many of the values in PwmConfiguration.xml (including some of the most important) are encrypted and not easily modified. I tried digging through the source code to find how the encrypted values are generated so I could generate them manually on the puppetmaster but haven't had any luck so far.

Rather than continuing down that path, I'd like to propose four additional commands for the PWM command-line module:
* `VerifySetting -key=<setting key> -value=<value> ...` - this command should exit with a status of 0 if the current value of the queried setting is equal to the provided value, and 1 otherwise. For example, `command.sh VerifySetting -key=ldap.proxy.password -value=123456`. For arrays, pass `-value` more than once. 
* `ChangeSetting -key=<setting key> -value=<value> ...` - this command adjusts the in-memory 'candidate' configuration so that the specified setting will be set to the specified value, if the configuration is subsequently saved; this is like using the Configuration Editor but not clicking the save button.
* `SaveChangedSettings` - this command would save the in-memory changes to PwmConfiguration.xml and restart the server, much like clicking the save button in the Configuration Editor.
* `DiscardChangedSettings` - this command would discard the in-memory changes.

Commands like these would allow Configuration Management tools to manage the configuration of PWM without having to re-implement the configuration file encryption system to do it.

Possible alternatives would be a (documented) REST API for the Configuration Editor, or documentation for how the config-file encryption is implemented so it could compatible encrypted values could be created by other tools.

**Comment by mkkeffeler** [comment]
I am also having this issue. it makes it difficult to use this tool if I cannot produce the config myself automatically. Going through the UI each time is time consuming.

**Comment by theonemcdonald** [comment]
Second. We need this for orchestration and especially secrets management (like integrating with Hashicorp Vault).

**Comment by jrivard** [comment]
You can write to password fields using plaintext like:

<value plaintext="true">password</value>

The value will be encrypted on the next save.   Touching/modifiying the config file causes an application restart.

**Comment by philomory** [comment]
@jrivard That is absolutely not sufficient; unless there is a way to keep PWM from replacing the plaintext with the ciphertext, this will result in orchestration restarting PWM every 30 minutes. Without the ability to validate that the currently stored password matches the intended value, the tooling must assume it does not match and reset it every time it runs.

That said, given the how intractable PWM is for configuration management and orchestration tools, it may be that PWM simply isn't targeted at our use case. LTB-project's Self-Service Password may be a better fit for our organization.

**Comment by jrivard** [comment]
PWM will only save the config file if edited and saved in the UI.  Otherwise it won't be modified by PWM.  

We're working on changes to the security config model hence the reluctance to develop APIs around it.   I'm not sure how an XML file is intractable but suit yourself.
