### ISSUE TITLE
How to use default applicationPath after 41d74e35e139c8a9f15986c5e424d187f6472288?

### ISSUE THREAD

**Issue by ThrawnCA** [pwm-project/pwm#43]
We would like to continue using an ``applicationPath`` detected from the WEB-INF directory, but after 41d74e35e139c8a9f15986c5e424d187f6472288, how can this be achieved?

**Comment by mmarseglia** [comment]
+1

**Comment by jrivard** [comment]
It's not going to happen.  Writing files inside a war archive automatically violates the servlet spec.

**Comment by mmarseglia** [comment]
@jrivard the application fails to start unless I change applicationPath from the default, unspecified value.  How could I start the application with the default values?

**Comment by jrivard** [comment]
Did you read the environment setup guide?

https://www.pwm-project.org/pwm/public/reference/environment.jsp

**Comment by mmarseglia** [comment]
@jrivard thank you for posting that!  I didn't see that document and was going off the installation instructions linked in the README.
