### ISSUE TITLE
Locked users cannot change passwords while locked - Change password button is disabled.

### ISSUE THREAD

**Issue by LucasLichte** [pwm-project/pwm#436]
My previous posting of this issue was closed without response.  Please at least respond as to why the issue is being closed.

In the forgotten password module, when a user successfully verifies their identity without authenticating to LDAP (we're using challenge questions and OTP Email), they are taken to a page that gives them an option to unlock their password or change and unlock their password. The latter button is always disabled - users must choose unlock their password, then go back through the Forgotten Password module which, with an unlocked user, will forward them to Change Password.

Verified with Chrome and IE, Active Directory LDAP backend.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.  This is not a help request system.
