### ISSUE TITLE
PWM build fails on Ubuntu 16.04  (Workaround included)

### ISSUE THREAD

**Issue by SamCN2** [pwm-project/pwm#438]
**Describe the bug**
During execution of mvn clean project, Maven fails with the following in the console output:
`
Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
`

**To Reproduce**
1. Follow instructions in Readme.md
2. Run:  mvn clean project
3. Wait for failure and process termination, just prior to the text output, find string: `SurefireBooterForkException`

**Expected behavior**
Successful compilation

**Screenshots**
`
Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /var/lib/jenkins/workspace/pwm/pwm-cr && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /var/lib/jenkins/workspace/pwm/pwm-cr/target/surefire/surefirebooter8681849147248875105.jar /var/lib/jenkins/workspace/pwm/pwm-cr/target/surefire 2018-11-14T20-52-35_490-jvmRun1 surefire5288590592784018954tmp surefire_0198947125217397440tmp
Error occurred in starting fork, check output in log
Process Exit Code: 1
`

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Solution/Workaround**
Place the following in the environment prior to mvn execution:
`
_JAVA_OPTIONS=-Djdk.net.URLClassPath.disableClassPathURLCheck=true mvn clean package
`

**Reference**

A web search for : `Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter` found the following resource:
`https://stackoverflow.com/questions/50661648/spring-boot-fails-to-run-maven-surefire-plugin-classnotfoundexception-org-apache`

Adding the `_JAVA_OPTIONS` solved the issue for me.

**Comment by jrivard** [comment]
This seems to be a bug with Ubuntu Java / Maven, I don't think there's anything to fix in PWM.
