### ISSUE TITLE
Cannot create field selecting field type

### ISSUE THREAD

**Issue by giorgiocanale** [pwm-project/pwm#44]
Hi, with version 1.8 it's not possible to create fields (on new user form, guest registratin form, ecc.) and select the type as was for version 1.7. The most notable absence is the "select" type.
Odd thing is that if I change manually the xml and restart pwm the interface is able to manage a field of type "select" (eg. adding values, removing values from the table) but it's not possible to create new one.

**Comment by jrivard** [comment]
It should be fixed as of current builds.
