### ISSUE TITLE
NullPointerException when overriding webjar files in ResourceFileServlet

### ISSUE THREAD

**Issue by ThrawnCA** [pwm-project/pwm#442]
**Describe the bug**
`ResourceFileServlet::handleWebJarURIs` constructs a File from the return value of `servletContext.getRealPath` without checking it for null. If the servlet context is unable to translate the path, this will result in a NullPointerException.

**To Reproduce**
1. Start a vanilla instance of PWM.
2. Go to 'public/resources/nonce-<nonce value here>/webjars/dojo/dojo.js'
3. Server error

**Expected behavior**
A JavaScript file should appear.

**Desktop (please complete the following information):**
 - OS: Solaris
 - Browser: Chromium
 - Version: 70.0.3538.77

**Comment by jrivard** [comment]
im not able to reproduce this using current build...

**Comment by ThrawnCA** [comment]
I'm not sure what's different about our setup; perhaps the fact that we're using Jetty? However, this NPE consistently occurs when we try to run a vanilla PWM version.

The code has moved to `ResourceFileRequest.java` now, but it works the same way and fails at the same point: it assumes that `servletContext.getRealPath` will return a non-null value, but for us it's sometimes null. Note that the ServletContext documentation does specify that `getRealPath` can return null.

I can provide an updated pull request if it would help?

**Comment by jrivard** [comment]
If the servlet container is returning null, then the resource servlet (among other things) won't work, so not sure what the point of changing this is...   I haven't tried running PWM on jetty.

**Comment by ThrawnCA** [comment]
Well, I don't know all the internal details of what the application is loading, but handing the NPE does make it work.
