### ISSUE TITLE
Helpdesk token verification broken by recent change

### ISSUE THREAD

**Issue by adam-bishop** [pwm-project/pwm#445]
**Describe the bug**
Helpdesk token verification has been broken by a recent change. My best guess is that it's 0e9d51e635d8ba449a4ae9155ae9f8326091f257 that has caused the regression based on timing.

On builds with the old UI, token verification works as expected. With builds using the updated UI, tokens are sent to users, but they are not able to be verified (see screenshots).

I've tested the following nightly nightly .war builds, using identical configs (just redeploying the WAR each time):
* 2018-12-10 - Broken
* 2018-11-29 - Broken
* 2018-11-28 - Works
* 2018-11-27 - Works

I also a config item may be broken in the helpdesk too, though I've not checked when it stopped working - so far I've noticed that:
* "Enforce User Password Policy" seems to be ignored (always true)

The XML config reflects the UI config, so the changes are being persisted.

**To Reproduce**
1. Deploy PWM, enable helpdesk module, configure email verification
2. Find a user, attempt to verify via email
3. Enter code in UI and submit

**Expected behaviour**
The verification token should be accepted.

**Screenshots**
<img width="429" alt="screenshot 2018-12-11 23 02 15" src="https://user-images.githubusercontent.com/1225481/49836290-ff4f2280-fd99-11e8-9a7b-6589f0a322d8.png">
Failure with new UI.

<img width="437" alt="screenshot 2018-12-11 23 10 31" src="https://user-images.githubusercontent.com/1225481/49836764-cadc6600-fd9b-11e8-9f85-bcbfaa8e8d5e.png">
Success with old UI.

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser Chrome
 - Version 70

**Additional context**
No relevant errors are logged during failure so far as I can tell, but might have something useful that I can't see:
https://gist.github.com/adam-bishop/6a125bc51d1de7297ce0557a60f28887

The logs were captured from an instance running the 2018-12-10 nightly and show the token being successfully sent, but not being verified.

**Comment by jrivard** [comment]
Should be fixed in current builds, please re-open if still an issue with current builds.
