### ISSUE TITLE
5049 ERROR_NEW_USER_FAILURE thrown when user tries to register

### ISSUE THREAD

**Issue by neb382** [pwm-project/pwm#446]
When "some" user tries to register after putting the veriification code, the error 
5049 Unable to create the new user is shown, 

The pwm log shows the following line
5049 ERROR_NEW_USER_FAILURE (unexpected ldap error setting temporary password for new user entry: javax.naming.OperationNotSupportedException

I assume that the password strength is not meeting our active directory policy but okay for pwm. 

The Password Policy Source is set to "LDAP"

PWM 1.8 is running on tomcat 8.5 (Windows 2012R2)
Problem occurs in any Browser.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general mailing list.
