### ISSUE TITLE
Errors in StoredConfiguration.xsd r943

### ISSUE THREAD

**Issue by michelgre** [pwm-project/pwm#45]
Hello,

When I load the project under Eclipse, I get errors on StoredConfiguration.xsd, and indeed it seems to me that they are errors.

1) The XML declaration says: encoding="utf-16" but the actual content is obviously utf-8.
2) The element PwmConfiguration is a complexType that lists directly several elements, without any xsd:sequence tag.

Am I wrong ?

**Comment by jrivard** [comment]
The storedconfiguration.xsd isn't valid or correct.  It's not used anywhere in the code.  It should probably be removed or fixed.

**Comment by michelgre** [comment]
Thank you for the explanation ! (Hum better late than never sorry)
