### ISSUE TITLE
Inproper PKI Trust Management for SMS Gateway

### ISSUE THREAD

**Issue by oruff** [pwm-project/pwm#457]
**Describe the bug**
If the **SMS Gateway Certificates** are left empty, the connection fails, even if the CA who issued the SSL certificate of the SMS Gateway are trusted in Java (cacerts).

**To Reproduce**
1. Go To Settings / SMS / SMS Gateway
2. Configure the settings **with** Certificate import
3. Click on "Test SMS Settings": you should be able to send a test SMS
4. Clear the Imported Certificates 
5. Click on "Test SMS Settings": you'll receive:
_unable to send message: 5078 ERROR_SMS_SEND_ERROR (error while sending SMS, discarding message: 5057 ERROR_SERVICE_UNREACHABLE (error while making http request: java.security.cert.CertificateException: server certificate {subject=CN=messaging.powermemobile.com} does not match a certificate in the configuration trust store.))_

**Expected behavior**
If the **SMS Gateway Certificates** are left empty, the PwmHttpClient should use the TrustStore of the JVM, like for LDAP configuration.
Note: Trusting the end entity certificate is far from PKI best practices. Furthermore, with Let's Encrypt issued certificates that are renewed every two months, it's impossible to use.

**Comment by jrivard** [comment]
This should be fixed in current builds.  Only the CA cert is imported, and if no cert is configured the java trustmanager is used.
