### ISSUE TITLE
Regression: Forgotten Password feature does not send emails

### ISSUE THREAD

**Issue by ThrawnCA** [pwm-project/pwm#462]
**Describe the bug**
When we used the Forgotten Password feature, password reset emails are not sent. No errors are logged, but the mail relay does not show any traffic.

**Additional context**
This worked correctly as at commit c9b007753332f1e234260501aafe3536f1270402 (September 2017) - we can simply swap in the old WAR file and it works - but is broken as of f3798cf97a8de493f4e74f026cc382535b796db5.

**Comment by wowhiren** [comment]
please find solution on this one
https://infogittech.blogspot.com/2019/07/how-to-setup-self-password-management.html

**Comment by ThrawnCA** [comment]
@wowhiren There are several significant problems with that, including the inadvisability of disabling firewalls and SELinux, the lack of any specific instructions related to sending emails, and the fact that we're running on Solaris and Jetty rather than Centos and Tomcat.

**Comment by jrivard** [comment]
@ThrawnCA if this is still an issue in current builds please provde relevent log info, I haven't seen any other reports of email issues.

**Comment by ThrawnCA** [comment]
Followed up with more specifics in #545.
