### ISSUE TITLE
PWM 5045 | An error occurred during the save of your response questions | with Active Directory

### ISSUE THREAD

**Issue by slanziner** [pwm-project/pwm#464]
An error occurred during the save of your response questions. Please contact your administrator. { 5045 ERROR_WRITING_RESPONSES (response storage only partially successful; attempts=1, successes=0, detail={"LDAP":"error saving responses via LDAP, error: 5045 ERROR_WRITING_RESPONSES (error writing user responses to ldap attribute 'pwmResponseSet': javax.naming.NoPermissionException: [LDAP: error code 50 - 00002098: SecErr: DSID-03150F93, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\u0000])"}) }

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
