### ISSUE TITLE
No error message in changepassword.jsp

### ISSUE THREAD

**Issue by DidiMolle** [pwm-project/pwm#466]
Hi all,

when a user enters a new password that is not accepted by the AD Domain Controller, and thus the password cannot be changed, there is no error message displayed on the sceen.
Instead, the user sees the same page again where he/she can enter the new password again. (changepassword.jsp)

Is this the expected behavior? Shouldn't there be an error message?

Regards
  Dieter

**Comment by jrivard** [comment]
Please try witht he most recent build and re-open if this is still an issue.
