### ISSUE TITLE
Invalid URL in some buttons --> private/command

### ISSUE THREAD

**Issue by puzich** [pwm-project/pwm#468]
If I try to change my password and click the cancel buttons the URL is directed to /private/command and a white page appears. In Safari Browser a file named "command" is downloaded.

**Comment by jrivard** [comment]
Please try the most recent build and re-open if this is still an issue.

**Comment by puzich** [comment]
Yesterday I tried the newest build (Snapshot: 2019-05-01T07_23_01Z). Same issue as before.
