### ISSUE TITLE
Reverse proxy using IIS

### ISSUE THREAD

**Issue by mikt** [pwm-project/pwm#472]
Hi,
I'm using a reverse proxy on a site configured in IIS, to forward all requests to http://localhost:8085/pwm (my pwm instance).

Unfortunately, all requests ends up in a 404.
Not sure if this is a pwm instance problem, or a general tomcat issue.

Is there any documentation for this?

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
