### ISSUE TITLE
PWM Erro 5015 -5015 ERROR_INTERNAL

### ISSUE THREAD

**Issue by 96737-3982** [pwm-project/pwm#476]
Hello
 I'm having trouble setting up PWM, I can not follow the error below.

I'm implementing PWM on a 16.04 LTS ubuntu server.
 Apache / 2.4.18
openjdk version 1.8.0_191

An error has occurred. If this error occurs repeatedly please contact your help desk.

5015 ERROR_INTERNAL (unexpected error during action handler for 'password.pwm.http.servlet.configguide.ConfigGuideServlet:ldapHealth', error: The Content already has an existing parent "PwmConfiguration")
OK

**Comment by rjd2745** [comment]
I'm very new to PWM as of yesterday.  I get the same error on both Ubuntu 18.10 and Windows 10 installs.  I'm going to try an older build later today.

**Comment by rjd2745** [comment]
Nevermind I just tried build 2019-03-04T08_01_08Z and it worked in Windows 10.

**Comment by rjd2745** [comment]
Build 2019-03-12T14_16_38Z is the newest build I can use that doesn't give me the above error when connecting to Active Directory.

**Comment by jrivard** [comment]
fixed in commit 815c6fbec267c2e0e9f57f26da9c92e242e05535.

**Comment by 96737-3982** [comment]
Good morning, Jason.

I'm now starting to understand and tweak llinux with mensione I'm working with Ubuntu 16.04 LTS,
I appreciate your help.
but I'm having trouble with where to put this command line.
Could you please help me?
