### ISSUE TITLE
5015 ERROR Internal

### ISSUE THREAD

**Issue by 96737-3982** [pwm-project/pwm#480]
5015 ERROR_INTERNAL (erro inesperado durante o manipulador de ação para 'password.pwm.http.servlet.configguide.ConfigGuideServlet: ldapHealth', erro: o Conteúdo já tem um pai "PwmConfiguration")

**Comment by Rozzly** [comment]
This is an issue with the latest build. Use  2019-03-16T03_43_58Z/ found here: https://www.pwm-project.org/artifacts/pwm/2019-03-16T03_43_58Z/
