### ISSUE TITLE
Email Address has invalid characters

### ISSUE THREAD

**Issue by laiclair** [pwm-project/pwm#483]
New user registration module is not accepting email with underscore "_" and end up with:
"Email Address has invalid characters"

Snapshot from : 2019-03-16T03_43_58Z

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.  This is not a bug.

**Comment by hdeadman** [comment]
E-mail addresses can have underscores... the company I work at uses lastname_firstname@xyz.com for their e-mail naming convention. Is it not a bug because the regular expression is configurable? It appears that the default regex for email is still ```^[a-zA-Z0-9 .,'@]*$```

**Comment by BloodyIron** [comment]
@hdeadman not sure if you still need a solution but: https://github.com/pwm-project/pwm/issues/719#issuecomment-3216227259
