### ISSUE TITLE
Error saving settings

### ISSUE THREAD

**Issue by 96737-3982** [pwm-project/pwm#484]
Hello
I'm having trouble setting up PWM, I can not follow the error below.

I'm implementing PWM on a 16.04 LTS ubuntu server.
Apache / 2.4.18
openjdk version 1.8.0_191

PWM -  1.7

configuraçoes Editar
Erro ao salvar as configuraçoes

Error saving settings

![image](https://user-images.githubusercontent.com/49238372/57462361-157ce400-724f-11e9-9eb1-fb1b6c2d0a19.png)

**Comment by T3chGuy77** [comment]
Were you able to figure this out? Did you follow my wiki guide listed here?

**Comment by T3chGuy77** [comment]
https://github.com/pwm-project/pwm/wiki/Installation-on-Ubuntu-Server-16.04-LTS

**Comment by 96737-3982** [comment]
Yes, I followed the installation guide but I still have this problem, is there a version of PWM that is unstable?

**Comment by T3chGuy77** [comment]
Not that I know of, we're on the current version. We actually upgraded the server to 18.04 and the current version of PWM is still working. Right after producing the error, check the logs. /var/logs/ and the apache logs. /var/log/apache2/ .   This may clue you in to what is wrong. To me this is probably a permissions issue to the config file or database.

**Comment by 96737-3982** [comment]
Hello
I performed all the tests as requested, since I still have an apache error.
 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.


![image](https://user-images.githubusercontent.com/49238372/57790162-91c06d00-7710-11e9-9d16-5a19cf3fcd17.png)

**Comment by T3chGuy77** [comment]
What version of PWM do you have? What OS did you install on?

Also that Apache2 error is just a warning and can be ignored or follow this link to get rid of the warning:  https://askubuntu.com/questions/256013/apache-error-could-not-reliably-determine-the-servers-fully-qualified-domain-n/256018

**Comment by T3chGuy77** [comment]
Ah nevermind. Upgrade to the current version of PWM, you are on version 1.7 and 1.8 is th current version.

https://www.pwm-project.org/artifacts/pwm/

**Comment by 96737-3982** [comment]
esse erro consegui resolver.

Qual versão do PWM você tem? Qual sistema operacional você instalou?

Também que o erro Apache2 é apenas um aviso e pode ser ignorado ou siga este link para se livrar do aviso: https://askubuntu.com/questions/256013/apache-error-could-not-reliably-determine-the-servers -fully-qualificado-domínio-n / 256018

**Comment by 96737-3982** [comment]
irei atualizar a versão como solicitado.

Ah deixa pra lá. Atualize para a versão atual do PWM, você está na versão 1.7 e 1.8 é a versão atual. Houve um bug de volta e acho que foi isso e agora está consertado. Também esta seção é para relatórios de bugs e não problemas de instalação. Da próxima vez, poste seus problemas para

https://groups.google.com/forum/#!forum/pwm-general

Link para a página de atualizações 
https://www.pwm-project.org/artifacts/pwm/
