### ISSUE TITLE
Password Recovery Question has Invalid Validation

### ISSUE THREAD

**Issue by toadzky** [pwm-project/pwm#485]
**Describe the bug**
When selecting the password recovery question `What city/town were you born in?`, it refuses to accept answers with "City" as part of the name.

**To Reproduce**
Choose the "where were you born" question, answer it with something containing "city". Fill out 3 additional questions, see the error message about not being able to use part of the question in the answer.

**Expected behavior**
Locations such as "New York City", "Carson City", etc should be allowed as answers.

**Screenshots**
![image](https://user-images.githubusercontent.com/2286682/58030869-956f3d80-7adc-11e9-8688-7febe91341c3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 74

**Comment by jrivard** [comment]
Please ask for help on the pwm-general group.  This is not a bug.
