### ISSUE TITLE
after configuration unable to login

### ISSUE THREAD

**Issue by mahmedinuae** [pwm-project/pwm#486]
DO NOT FILE AN ISSUE FOR HELP.  This issue system is not for help requests and such issues will be deleted.

Instead, please ask for help on the [PWM-General Google Group](https://groups.google.com/group/pwm-general).

After i have saved the own configuration, when i try to login to the portal it gives me this issue.

An error has occurred. If this error occurs repeatedly please contact your help desk.

5015 ERROR_INTERNAL (unexpected error during ldap search (profile=default), error: 5015 ERROR_INTERNAL (ldap error during searchID=14, error=javax.naming.PartialResultException, cause:javax.naming.CommunicationException: MEDIAONE.DXB:636, cause:javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: server certificate {subject=CN=M1DC1.mediaone.dxb} does not match a certificate in the PWM configuration trust store., cause:java.security.cert.CertificateException: server certificate {subject=CN=M1DC1.mediaone.dxb} does not match a certificate in the PWM configuration trust store.))
![PWM error](https://user-images.githubusercontent.com/50863033/58077896-8bbe0680-7bbe-11e9-8608-af4c95a5582a.JPG)

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
