### ISSUE TITLE
Openldap and MS Active Directory password writing simultaneous

### ISSUE THREAD

**Issue by heinz54** [pwm-project/pwm#487]
Feature Request for PWM.

Our company is currently using PWM for password changes to openldap it work perfectly
So we need to implement MS active directory, recently password our Global company requires us to integrate with their directory. So we implement MS AD and AAD .

So no our current problem is maintaining password using PWM for OpenLDAP and for MS AD reset the password manually and a different password for the account as well.

Because with this PWM you create different profiles with the different directory. It is possible for you to link the OpenLDAP and AD directory together so that when the password is changed/reset/forgot it writes it to both directories.

Having this kind of tools will much be appreciated.

**Comment by jrivard** [comment]
PWM is not, and never will be, a directory synchronization tool.
