### ISSUE TITLE
Password reset at windows logon screen

### ISSUE THREAD

**Issue by mahmedinuae** [pwm-project/pwm#489]
**Is your feature request related to a problem? Please describe.**
if a user is locked out of his computer. he has to go to another computer and go to the portal and reset his password. 

**Describe the solution you'd like**
Instead there should be an option on windows log on screen where user should be able to select to reset his apssword by answering secret questions

**Describe alternatives you've considered**
nothing yet
**Additional context**

**Comment by jrivard** [comment]
Since this requires a windows client to acheive, it's unlikely the PWM project will ever do this.  You might be interested in the commercial version of PWM at http://netiq.com/sspr which has a component called CLE or Custom Login Extensions that allow windows clients to do this.
