### ISSUE TITLE
Can not connect to remote server: 5059 ERROR_CERTIFICATE_ERROR (unable to read server certificates from host=

### ISSUE THREAD

**Issue by 3iiko** [pwm-project/pwm#491]
Hello,

i have the issue to configure the wpm. 

At the ldap server page, i'm unable to connect to the Windows AD server. I have this message : 

Can not connect to remote server: 5059 ERROR_CERTIFICATE_ERROR (unable to read server certificates from host=192.168.1.243, port=636 error: Couldn't kickstart handshaking) fields: [unable to read server certificates from host=192.168.1.243, port=636 error: Couldn't kickstart handshaking]

I assume i have to import the certificate, so i created a certificate from the domain controller (192.168.1.243) and exported it.
But now, i don't know how to use it. Do i have to import the certificate to wpm ? If yes, how i can do that.

I'm quite new to use linux, so if you can write me the command line it will be great.

WPM install via Tomcat9 on Ubuntu 19

Thanks for your help.

Have a good day.

**Comment by 3iiko** [comment]
Any idea, please ?

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
