### ISSUE TITLE
5015 ERROR_INTERNAL (unexpected error during ldap search (profile=default), error: 5015 ERROR_INTERNAL

### ISSUE THREAD

**Issue by galeinslopez** [pwm-project/pwm#492]
DO NOT FILE AN ISSUE FOR HELP.  This issue system is not for help requests and such issues will be deleted.

During the configuration process (Wizard) for the integration with an Active Directory of Microsoft, in the aggregation window of Administrators group, the following error is obtained:

An error has occurred. If this error occurs repeatedly please contact your help desk.

5015 ERROR_INTERNAL (unexpected error during ldap search (profile=default), error: 5015 ERROR_INTERNAL (ldap error during searchID=0, error=javax.naming.PartialResultException, cause:javax.naming.CommunicationException: mspcentral.ec:636, cause:javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching domain.com found., cause:java.security.cert.CertificateException: No subject alternative DNS name matching domain.com found.))

Can you please help me by guiding me about the possible solution to apply?

Instead, please ask for help on the [PWM-General Google Group](https://groups.google.com/group/pwm-general).

**Comment by jrivard** [comment]
This is not a bug, please ask for help on the pwm-general google group.
