### ISSUE TITLE
Installation of PWM 1.8+ on RHEL7+ ?

### ISSUE THREAD

**Issue by topfuel-florida** [pwm-project/pwm#495]
Has anyone gotten this to run on Tomcat in RHEL7 or newer? My current Production is PWM 1.7.x on RHEL 6.
I've followed the installation for Ubuntu and gotten both PWM 1.8 and 1.9 to start. For the life of me can't figure out why I'm still getting java errors with RHEL7:
java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspSourceImports
![Tomcat_Java_ClassNotFoundException](https://user-images.githubusercontent.com/27973251/60744593-571ec800-9f3c-11e9-8c79-9973830e9799.PNG)

**Comment by windowsrefund** [comment]
Why was this closed?

**Comment by topfuel-florida** [comment]
wondered the same thing. writing themselves out of utilization in Government and many other heavily regulated spaces by not helping get it running on RHEL again. Ubuntu works fine and older PWM 1.7 runs on RHEL 5/6/7 just fine. So what's wrong with PWM 1.8 and 1.9 on current RHEL?

**Comment by hydrian** [comment]
I'm getting it with Ubuntu 16.04's Tomcat8 too.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.  This is not a bug.
