### ISSUE TITLE
Prompt text

### ISSUE THREAD

**Issue by vdiscipio** [pwm-project/pwm#498]
We recently brought up the 1.9 version without issue.  We are a Microsoft show and the majority of our folks have already installed the Microsoft authenticator app and I want to change the text that appears during setup of the mobile authenticator app saying that the Microsoft Authenticator App will work too.  I have looked through all the messages/text/error areas in the configurator and searched the PwmConfiguration.xml for the text and cannot find where to edit it.  

Any help is appreciated. 

Thanks

**Comment by jrivard** [comment]
Please ask for help on the pwm-general group
