### ISSUE TITLE
Add open source captcha (no third party)

### ISSUE THREAD

**Issue by Perflyst** [pwm-project/pwm#501]
**Is your feature request related to a problem? Please describe.**
ReCaptcha is a third party service from Google. This is bad for privacy.

**Describe the solution you'd like**
Some local captcha, e.g. counting numbers, answering a question etc.

**Comment by BloodyIron** [comment]
Those mechanisms you describe are now extremely defeatable by bots. While I agree with you we need a local mechanism to prove humanity, there's very established (and good) reasons why reCaptcha 2 (or 3, losing count) is the primary anti-bot mechanism.

I do agree, PWM should have a local way to do this, but it needs far more technical complexity than you're describing here.

**Comment by Perflyst** [comment]
There is an interesting solution in https://invidio.us
Click login and enter completely random access details. You get a captcha with a clock.

**Comment by BloodyIron** [comment]
@Perflyst okay that's really cool.

**Comment by jrivard** [comment]
Closing as to ambiguous.  If a specific implementation is suggested it will be considered.
