### ISSUE TITLE
HTTP Status 500 - org/apache/jasper/runtime/JspSourceImports

### ISSUE THREAD

**Issue by bmmgithub** [pwm-project/pwm#505]
[pwm error.txt](https://github.com/pwm-project/pwm/files/3599370/pwm.error.txt)

Hi,

I'm trying to install pwm in a CentOS-7 server, but cannot get pwm working,
Environment. :
CentOS 7-6.1810.2
Apache Tomcat/7.0.76
JVM 1.8.0_222-b10
php 7.3.9-1

I have tried to deploy both pwm-1.9.0 and pwm-1.9.1 but when typing "ip-adress:8080/pwm"
I get :
HTTP Status 500 - org/apache/jasper/runtime/JspSourceImports
See attached file pwm error.txt for complete error report.

Any help is appreciated.

/B

**Comment by jrivard** [comment]
tomcat 8x required.
