### ISSUE TITLE
http 500

### ISSUE THREAD

**Issue by bmmgithub** [pwm-project/pwm#507]
Hi,

I'm trying to install pwm in a CentOS-7 server, but I cannot get pwm working,
Environment. :
CentOS 7-6.1810.2
Apache Tomcat/8.5.45
JVM 1.8.0_222-b10
php 7.3.9-1

I have tried to deploy both pwm-1.9.1.war and /pwm-2.0.0-SNAPSHOT.war
but when typing "ip-adress:8080/pwm" I get (after a long wait) :

PWM

5083 ERROR_ENVIRONMENT_ERROR (application path is not specified)

An error with the application environment has prevented the application from starting.

Found this in localhost_accessLog :
10.43.244.68 - - [19/Sep/2019:11:49:16 +0200] "GET /manager/html HTTP/1.1" 401 2562
10.43.244.68 - admin [19/Sep/2019:11:49:20 +0200] "GET /manager/html HTTP/1.1" 200 21647
10.43.244.68 - - [19/Sep/2019:11:49:45 +0200] "GET /pwm HTTP/1.1" 302 -
10.43.244.68 - - [19/Sep/2019:11:50:15 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:11:51:05 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:11:52:25 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:11:53:15 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:11:54:35 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:11:55:25 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:11:56:46 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:11:57:36 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:11:58:56 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:11:59:46 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:12:01:06 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:12:01:56 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:12:03:16 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:12:04:06 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:12:05:27 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:12:06:17 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583
10.43.244.68 - - [19/Sep/2019:12:07:37 +0200] "GET /pwm/ HTTP/1.1" 500 1000
10.43.244.68 - - [19/Sep/2019:12:08:27 +0200] "GET /pwm/public/resources/style.css HTTP/1.1" 200 28583

**Any help is appreciated.**

/B

**Comment by bmmgithub** [comment]
and also this in catalina.out :
2019-09-19T12:08:42.641Z, ERROR, filter.RequestInitializationFilter, unable to satisfy incoming request, application is not available
2019-09-19T12:09:32.719Z, ERROR, resource.ResourceFileServlet, unable to satisfy request using standard mechanism, reverting to raw resource server
2019-09-19T12:10:52.880Z, ERROR, filter.RequestInitializationFilter, unable to satisfy incoming request, application is not available
2019-09-19T12:11:42.969Z, ERROR, resource.ResourceFileServlet, unable to satisfy request using standard mechanism, reverting to raw resource server

**Comment by bmmgithub** [comment]
Can you please help with this, not just close it with no comment?

Regards,
/B

**Comment by lotusnoir** [comment]
I had the same issue and the answer is quite simple, 
once you install the pwm.war on the tomcat dir (ex: /var/lib/tomcat9/webapps/) then you need to edit the web.xml that its created:

` vim /var/lib/tomcat9/webapps/pwm/WEB-INF/web.xml`

and put the absolute path on the applicationpath param

```
        </description>
        <param-name>applicationPath</param-name>
        <param-value>**/var/lib/tomcat9/webapps/pwm/**</param-value>                                                                               
    </context-param>
```
 OR you set an env variable:

`export PWM_APPLICATIONPATH='/var/tomcat/webapps/pwm/`
