### ISSUE TITLE
PWM installation on stand alone windows 2016 server

### ISSUE THREAD

**Issue by nicovatteroni** [pwm-project/pwm#524]
HI,
I need help cause I want to install PWM (latest version) on a stand alone Windows server 2016.
I've downloaded every setup (JRE,Apache,etc,etc,...)like I found on the very small documentation for windows (https://github.com/pwm-project/pwm/wiki/Installation-on-Windows-OS) but I've still problem in particular with 2 steps : 
1) LDAPS certificate from my AD 2012 seems not working with PWM (I 've tried to import with the command on the prompt and putting the password "changeit" and every seems to be good from command line but the it seems that the appliance couldn't anyway contact LDAPS).Is there a manual or somethings more detailed to understand step by step what I've to do?
2)at the beginning I was intent on using the native database but then I saw that it was strongly discouraged for production environments (as is my case). There is a step-by-step manual for installing and configuring a free DB (for example mysql) for the pwm on windows 2016 environment (i.e. the same server on which the application is already installed)?
Thanks  a lot and excuse me if I'm doing this question on this space (I really don't know if there is a specific palce where I have to do request of help...)

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
