### ISSUE TITLE
When users delete the active directory of Microsoft

### ISSUE THREAD

**Issue by abdxj407** [pwm-project/pwm#526]
After deleting the user in the active directory, the user has previously saved the response information. When the user account is deleted, the same account is recreated. The account password can be reset by PWM using the response information of the previous user. But after a while, when the user logs in through PWM again, the response information is required to be provided again, which seems to be a bug

 VER:2.0

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
