### ISSUE TITLE
CAS Support?

### ISSUE THREAD

**Issue by mmoayyed** [pwm-project/pwm#53]
Hi, I noticed PWM has built-in CAS integration. What would it take to include this module inside a CAS deployment? Are there binary dependencies available for PWM?

**Comment by jrivard** [comment]
The cas integration in PWM is somewhat deprecated, and definitly not well maintained.  Since CAS now supports OAuth integration I'm not sure what value the java cas integration method has anymore.  I don't understand your dependency question.

**Comment by mmoayyed** [comment]
Mostly what I am interested in is: I'd want to directly include PWM in a CAS deployment. Not a separate project/build/deployment. When one deploys CAS, they automatically/optionally get PWM functionality in place. CAS can detect account statuses and notify users, but at that point, users would have to separately deploy PWM and I am interested to see if it can be included by default as a module.

**Comment by mmoayyed** [comment]
Example, a CAS deployer would declare in their same build configuration:

```
<dependency>
  <groupId>pwm</groupId>
  <artifactId>pwm</artifactId>
</dependency>
```

And they PWM in the same CAS webapp. Not really an integration question; more like what's it going to take to make this directly available and not as a standalone separate project.

**Comment by jrivard** [comment]
I really can't speak to what that would take.  Your on your own.   I have no plan to publish pwm on maven in the near future.
