### ISSUE TITLE
SSL certificate not importing 

### ISSUE THREAD

**Issue by fsadoon** [pwm-project/pwm#533]
***DO NOT FILE AN ISSUE FOR HELP OR TO ASK QUESTIONS.***  This issue system is not for help requests and such issues will be deleted.

Instead, please ask for help on the [PWM-General Google Group](https://groups.google.com/group/pwm-general).  If your not sure, it's better to ask on the pwm-general group before opening an issue here.

**Describe the bug**
when importing SSL KEY it doesn't work and doesn't appears 

**To Reproduce**
Steps to reproduce the behavior: N/A

**Expected behavior**
The Key to Appears in imported keys 
**Screenshots**

![image](https://user-images.githubusercontent.com/42034405/74563938-eeda9f00-4f7e-11ea-8ae1-a37d79086907.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jrivard** [comment]
Are you using the latest docker container snapshot of PWM 2.0-SNAPSHOT?  Please post container logs.

**Comment by fsadoon** [comment]
hi there, 
yes am using the latest docker container PWM 2.0-SNAPSHOT,

logs are attached 

Note : i removed my configuration and ran the container from scratch 

[pwm.txt](https://github.com/pwm-project/pwm/files/4208499/pwm.txt)

**Comment by fsadoon** [comment]
i tried Windows/Ubuntu and same is happening

**Comment by jrivard** [comment]
This container log doesn't have a configuration, thus it's using the default self-signed HTTPS cert.  Please attach a log of the container starting with an HTTPS certificate configured.

**Comment by fsadoon** [comment]
do you mean that i need to run the docker image with my cert ? like : 
docker run -v /host/path/to/certs:/container/path/to/certs -d IMAGE_ID "update-ca-certificates"

**Comment by fsadoon** [comment]
+ what if i want to deploy it on tomcat directly.. it still not taking the cert

**Comment by jrivard** [comment]
I've been able to reproduce an issue where the configeditor UI is not properly saving the cert during the import process.  I think that's what you were originally reporting....   Standby for a fix.

This issue only affects the docker container and onejar distro.  If you use the WAR file your on your own for configuring the HTTPS certificate, it won't be a config option in the configeditor.

**Comment by fsadoon** [comment]
Yup .. it works with the WAR file , struggled little bit to deploy it but eventually it works .. 
Appreciate your effort

**Comment by fsadoon** [comment]
Yup it works with the WAR file, struggled little bit in the deployment but eventually it works .. 

Appreciate your effort

**Comment by fsadoon** [comment]
BTW, in the war file .. i can use the search bar to get the HTTPS option :) so you might want to disable it

**Comment by jrivard** [comment]
fixed in db7c2ee968d0657f25dbf552bc942a06f6fc9ee4
