### ISSUE TITLE
Security question responses rejected because "too commonly used" 

### ISSUE THREAD

**Issue by zwets** [pwm-project/pwm#549]
**Description**
When setting security questions, responses erroneously appear to be checked against word lists. Entering a valid word triggers the error message _The response for question "XYZ" is too commonly used_.

**Steps to Reproduce**
1. Go to 'Setup Security Questions'
2. Select any question, e.g. 'What is your favourite vehicle?'
3. Enter 'bicycle' in the reponse field
4. The system gives error _The response for question "What is your favorite vehicle?" is too commonly used_
5. Change the response to e.g. 'prstqwit' or other gibberish
6. The system accepts the field

**Expected behavior**
Commonly used words should be accepted as responses to security questions.

**System**
 - Client: Firefox 76 on Ubuntu 20.04
 - Server: PWM 2.0.0-SNAPSHOT ba1ffb42 (2020-05-22) on Tomcat 8.5.55 on Ubuntu 16.04

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.  This is not a bug.

**Comment by zwets** [comment]
Thanks Jason, I notice now this was a duplicate of #338, which also has the solution.
