### ISSUE TITLE
Access permission error writing node heartbeat

### ISSUE THREAD

**Issue by ThrawnCA** [pwm-project/pwm#551]
**Describe the bug**
PWM logs warnings similar to:

    The cluster system can not operate normally: error writing node service heartbeat: 5079 ERROR_LDAP_DATA_ERROR (error writing node service data user 'cn=pwmtest,ou=users,dc=cas,dc=qld,dc=gov,dc=au (default)' attribute 'pwmData', error: javax.naming.NoPermissionException:  [LDAP: error code 50 - The entry cn=pwmtest,ou=users,dc=cas,dc=qld,dc=gov,dc=au cannot be modified due to insufficient access rights])

**Additional context**

Our LDAP access control is similar to:

    aci: (targetattr ="userpassword || telephonenumber || facsimiletelephonenumber || pwmResponseSet || pwmOtpSecret")(version 3.0;acl "Allow self entry modification";allow (write)(userdn = "ldap:///self");)

However, the line of code causing this warning (in `LDAPNodeDataService.java`, `writeNodeData`) appears to be attempting to add an attribute rather than update one.

**Comment by jrivard** [comment]
In LDAP parlanance there is only add or replace.  Both permissions are needed.  I don't know how AD interprets them.
