### ISSUE TITLE
Account Activation error message

### ISSUE THREAD

**Issue by gyang2300** [pwm-project/pwm#555]
**Is your feature request related to a problem? Please describe.**
When a user tries to activate an account that is already activated, he gets no error message. The screen refreshes back to the login screen. This is not helpful.

**Describe the solution you'd like**
When a user tries to activate an account that is already activated, he should see some kind of error message. That way, he knows what happened. 

Perhaps, a customizable message or a message saying, "This account was previously activated and cannot be activated again." 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
