### ISSUE TITLE
Verification of token

### ISSUE THREAD

**Issue by rovki1135** [pwm-project/pwm#556]
Hi,

We make a pentest of pwm before lauching in production and we found a bug with the token.

If i request a password reset for my user, i receive a token and after i can reset. But if i use this token for another user, i can reset his password. Pwm validate the token but not the user who has demand the resquest. Is there a parameter for this ? Or it is a bug ?

Thanks for help,

Best regards,

**Comment by jrivard** [comment]
Yes the token bearer can reset the password.  That's the idea.  That's why you should use multiple verification methods.

If your talking about about token re-use, that can be done by using a token storage engine other than crypto and is set by default to expire tokens on use.

**Comment by rovki1135** [comment]
The SMS is not linked to the user. The attacker can reset a another user password whit his token.

**Comment by rovki1135** [comment]
![Capture](https://user-images.githubusercontent.com/61747965/85865372-11e74c00-b7c6-11ea-8a91-bc2539fa7050.PNG)
