### ISSUE TITLE
Maximum Characters From Previous Password has no effect

### ISSUE THREAD

**Issue by sistemistipat** [pwm-project/pwm#560]
I setup PWM with value of 3 on field "Maximum Characters From Previous Password".
But it has no effect because I can change only a character from the previous password and the system accept it.

I use CentOS 7, v2.0.0-SNAPSHOT, java 1.8.0_232-b09, Apache Tomcat/8.5.50.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
