### ISSUE TITLE
Not able to make secure LDAPs connection to Microsoft AD

### ISSUE THREAD

**Issue by somnath157** [pwm-project/pwm#570]
I am trying to configure my AD. Ldap connection without ssl to port 389 is working properly but with secured to port 636 not working.

I have installed a self signed certificate in Java.

Can not connect to remote server: 5059 ERROR_CERTIFICATE_ERROR (unable to read server certificates from host=cogneesol.ad.com, port=636 error: javax.net.ssl.SSLException: Connection reset, cause:java.net.SocketException: Connection reset) fields: [unable to read server certificates from host=cogneesol.ad.com, port=636 error: javax.net.ssl.SSLException: Connection reset, cause:java.net.SocketException: Connection reset]

**Comment by jrivard** [comment]
This error occurs when the PWM server can not reach port 636 on your server.  Please check your AD setup and ask for help in the google groups if issue is still occuring.
