### ISSUE TITLE
emailHealthCheck Error

### ISSUE THREAD

**Issue by markkrj** [pwm-project/pwm#575]
Testing e-mail settings from config editor fails.

1. Go to Settings ⇨ Email ⇨ Email Servers ⇨ default
2. Configure e-mail server settings.
3. Click on 'Test Email Settings'
4. Fill the form and click "Ok"

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 82

**Additional context**

Was able to fix replacing the following line:
https://github.com/pwm-project/pwm/blob/ea543c22476f09b8cb67452049b7799929d4215f/server/src/main/java/password/pwm/http/servlet/configeditor/ConfigEditorServlet.java#L679

By:
`final MacroMachine macroMachine = pwmRequest.getPwmSession().getSessionManager().getMacroMachine();`

I could make a pull request, but it seems that you don't review it (or at least, don't give feedback)

**Comment by jrivard** [comment]
This should be fixed in latest build, please re-open if it is not.
