### ISSUE TITLE
Dojo Library Vulnerability

### ISSUE THREAD

**Issue by Bails309** [pwm-project/pwm#580]
**Describe the bug**
Dojo version 1.15.0 is used on the site with 1 known medium vulnerability. Affected versions of this package are vulnerable to Prototype Pollution. The deepCopy method within dojo could be tricked into adding or modifying properties of Object.prototype

**To Reproduce**
(There are a few methods but I have used Google Lighthouse)
1. Go to any website running PWM using a Chromium based browser. 
2. Click F12
3. Scroll along the tabs to Lighthouse
4. Untick all bar 'Best Practices'
5. Click Generate Report
6. Scroll down to the bottom section which outlines Trust & Safety.
4. See vulnerability

**Expected behavior**
It would be expected that there are no vulnerabilities listed in the section.

**Screenshots**
![image](https://user-images.githubusercontent.com/60200588/97869103-c65f2480-1d08-11eb-9825-0064cebd0729.png)

**Desktop:**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 86

**Additional context**
Further reading around the library: https://snyk.io/vuln/npm:dojo?lh=1.15.0&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

**Comment by jrivard** [comment]
Current release is using dojo 1.16.3.

**Comment by Bails309** [comment]
The latest what I believe to be 'stable' version appears to be v1.9.1 which is what we are running and still has the vulnerability. 
![image](https://user-images.githubusercontent.com/60200588/97968887-2d3b1700-1db7-11eb-971e-f0c09df5a191.png)

![image](https://user-images.githubusercontent.com/60200588/97969056-670c1d80-1db7-11eb-8381-83bbcdd246dd.png)

Is this patched version of Dojo only available on the unstable builds section of PWM and if so is this likely to make it's way to a stable release soon?

Thanks
