### ISSUE TITLE
Group Membership not working on login

### ISSUE THREAD

**Issue by waltdjr** [pwm-project/pwm#581]
PWM Version | v2.0.0-SNAPSHOT bea543c2
Build Time | October 15, 2020, 1:50:16 AM EDT

After updating to the latest build, when I log in as an Administrator and Help Desk member, neither option show up on my "Authenticated Page"  There is no Help Desk option nor the Administration option.  If I go into the config and click "View Matches" the group members return for both Help Desk and Administrators groups.  If I add my user DN specifically, they show up again but for a group DN it seems to have stopped working on authentication.

Thanks,
WaltDjr

**Comment by jrivard** [comment]
This should be fixed in latest build, if not please re-open.
