### ISSUE TITLE
ExternalChangeMethod

### ISSUE THREAD

**Issue by jdelreal** [pwm-project/pwm#59]
Was this feature removed between 1.7.1 and 1.8.0 (there was no notice in history/change-log), if it was could it be re-added. Just installed and configured PWM 1.8.0 and notice Developer/Integration settings missing. Can no longer sync external NIS directory with AD changes via PWM.

Thanks

**Comment by jrivard** [comment]
It will not be re-added.  We no longer are maintaining any Java interfaces.  Instead you can use a change password action to invoke a web service.  You will need to convert your java plugin to a web service listener instead.
