### ISSUE TITLE
Error - sending authentication token by sms

### ISSUE THREAD

**Issue by JuanDoradoP** [pwm-project/pwm#591]
Hello,

I have implemented the pwm portal solution. Everything has been perfect, except the authentication through SMS token. To do this, I have used the MessageBird service.

However, when I try to use token sending by sms,
the message never reaches the user's phone.

I share some configurations that I have made for the issue of sending the token by sms:

![image1](https://user-images.githubusercontent.com/38574009/107707823-7e00bc80-6c90-11eb-8d1b-2da1050cdc0d.PNG)
![image2](https://user-images.githubusercontent.com/38574009/107707825-7e995300-6c90-11eb-8770-543a1ca8c016.PNG)

I would really appreciate if someone could help me with this problem.

Juan David Paz.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
