### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by tamhankarni3** [pwm-project/pwm#594]
Hello Experts,

While searching for Self Password Reset Tool, I came across PWM and planned to implement in our domain environment.
Currently I am using Windows Server 2016 STD server to deploy the application.
My Active Directory is configured to access SSL request on port 636.

I am getting attached error while configuring LDAPS with PWM.
I have tried importing cer file generated by domain with keytool command, wont help!!

  
![image](https://user-images.githubusercontent.com/62698391/109860382-17196680-7c84-11eb-8111-b7aa26a6b9a3.png)

**Comment by jrivard** [comment]
Closing for not following issue create instructions.

**Comment by tamhankarni3** [comment]
> Closing for not following issue create instructions.

whats wrong
