### ISSUE TITLE
How to modify and change branding

### ISSUE THREAD

**Issue by amdjml** [pwm-project/pwm#595]
Hi,

I would like to know how to edit the text page on the login screen, like branding and stuff. Right now it is very generic text and I would like to place our logo somewhere and also change the text. See below:

![Screen Shot 2021-03-04 at 3 39 40 PM](https://user-images.githubusercontent.com/875782/110027360-dd864100-7cff-11eb-849c-28b1d6638f51.png)

**Comment by jrivard** [comment]
Closed for not following issue template instructions.
