### ISSUE TITLE
Command configunlock => "C:\Program" not recognized as...

### ISSUE THREAD

**Issue by ragnodimaggio** [pwm-project/pwm#596]
**Describe the bug**
Even if JAVA_HOME is correctly populated, _command configunlock_ produces an error:
_Command Prompt Error 'C:\Program' is not recognized as an internal or external command, operable program or batch file_

**To Reproduce**

1. SETX /M JAVA_HOME "C:\Program Files\AdoptOpenJDK\jdk-11.0.10.9-hotspot" (or any other method)
2. from directory "C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\pwm\WEB-INF"
3. run command" configunlock

**Expected behavior**
PWM v2.0.0-SNAPSHOT b99db009 Command Line Utility
applicationPath=C:\pwm
environment initialized
success: configuration has been unlocked

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 standard
 - Firefox ESR 78.8
 - pwm-2.0.0

**Solution**
I modified the command.bat
Modified part: "%JAVA_HOME%\bin\java" (added double quotes)

**Comment by jrivard** [comment]
fixed in commit 6c02e460e7f99440b3300def7e377490fb7cc6c9
