### ISSUE TITLE
When picking the Korean locale, the Slovak flag appears

### ISSUE THREAD

**Issue by okjoekenny** [pwm-project/pwm#598]
When an user picks the Korean locale, the Slovak flag appears

I notice on the style sheet that the style for .flagLang_XX where XX would match the name of 
the png file.

For example french would be
.flagLang_fr {
    background-image: url(/pwm/public/resources/flags/png/fr.png);
}

But for Korean it is 
.flagLang_ko {
    background-image: url(/pwm/public/resources/flags/png/sk.png);
}

Following the naming convention, I would assume the flag file would be call ko.png.
There is no ko.png file to be found

The  sk.png is for Slovak

**Comment by okjoekenny** [comment]
In the file localeselect.jsp , I see the following code that looks like it builds the locale list


<%
    List<Locale> localeList = Collections.emptyList();
    PwmApplication localeselect_pwmApplication = null;
    try {
        localeselect_pwmApplication = PwmRequest.forRequest(request, response).getPwmApplication();
        localeList = localeselect_pwmApplication.getConfig().getKnownLocales();
    } catch (PwmException e) {
        /* noop */
    }
%>

Would anyone know where the data resides that is used to populated this list?

the file path to this file is 
pwm-master/src

**Comment by jrivard** [comment]
Closed for not following template instructions.
