### ISSUE TITLE
LDAP Search Filter Creation 

### ISSUE THREAD

**Issue by nomanrahman** [pwm-project/pwm#6]
File: FormUtility.java
Class: FormUtility
Function: ldapSearchFilterForForm
Problem Code: 
            if (objectClasses.size() == 1) {
                sb.append("(objectclass=");
                sb.append(objectClasses.iterator().next());
                sb.append(")");
            } else {
                sb.append("(|");
                for (final String objectClassValue : objectClasses) {
                    sb.append("(objectclass=");
                    sb.append(objectClassValue);
                    sb.append("("); ///////////////problem
                }
                sb.append(")");

Fixed Code:
            if (objectClasses.size() == 1) {
                sb.append("(objectclass=");
                sb.append(objectClasses.iterator().next());
                sb.append(")");
            } else {
                sb.append("(|");
                for (final String objectClassValue : objectClasses) {
                    sb.append("(objectclass=");
                    sb.append(objectClassValue);
                    sb.append(")");/////////////fix
                }
                sb.append(")");
            }

Thank you. ~NR.

**Comment by jrivard** [comment]
This has been fixed in the current trunk build.  Thank you for reporting the issue.
