### ISSUE TITLE
Updating exisiting pwm on ldap giving paging errors

### ISSUE THREAD

**Issue by duttonw** [pwm-project/pwm#60]
Hi,

Just letting you know that there seems to be no ability in the config editor to change the ldap.search.paging.enable flag and the ldap.search.pagining.size option which were added recently

I had to manually add these two settings to my PwmConfiguration.xml files to make pwm work correctly when running against openDJ.

Regards

William D.

    <setting key="ldap.search.paging.enable" syntax="BOOLEAN">
      <label>Attribute to use for ldap search paging enable</label>
      <value>FALSE</value>
    </setting>
    <setting key="ldap.search.paging.size" syntax="NUMERIC">
      <label>Attribute to use for ldap search page sizing</label>
      <default />
    </setting>

**Comment by jrivard** [comment]
You can set them in Settings -> Application -> App Property Overrides.

What did you change the values to?

**Comment by duttonw** [comment]
ldap.search.paging.enable i changed to false, but default its on auto or true and health check and login gave errors. I'll look into that area on monday, I was expecting these settings to be under the ldap section.
