### ISSUE TITLE
unable to obtain file lock on file

### ISSUE THREAD

**Issue by yule-sun** [pwm-project/pwm#607]
***DO NOT FILE AN ISSUE FOR HELP OR TO ASK QUESTIONS.***  This issue system is not for help requests and such issues will be deleted.

Instead, please ask for help on the [PWM-General Google Group](https://groups.google.com/group/pwm-general).  If your not sure, it's better to ask on the pwm-general group before opening an issue here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

when i am restart the tomcat9 service i got an error like the below, And i cann't access the website.
_2021-06-25T19:36:21Z, DEBUG, pwm.PwmEnvironment, unable to obtain file lock on file E:\pwm\applicationPath.lock
2021-06-25T19:36:21Z, DEBUG, pwm.PwmEnvironment, can't establish application file lock after 1m:59s, will retry;
2021-06-25T19:36:26Z, FATAL, pwm.PwmApplication, 5082 ERROR_STARTUP_ERROR (unable to obtain application path file lock)_

**Comment by jrivard** [comment]
Please ask for help on the google group.
