### ISSUE TITLE
Administrators Group

### ISSUE THREAD

**Issue by azura-vergo** [pwm-project/pwm#65]
hello,
i want to ask a question about  pwm1.8`s configuration.
i don`t know how to set "Administrators Group"
![image](https://cloud.githubusercontent.com/assets/8624914/14579872/9f3ef18a-03ec-11e6-840b-839ac8190993.png)

in my ldap server, a group with two users(with administrator permission) had been created.
![image](https://cloud.githubusercontent.com/assets/8624914/14579876/cbc97ebe-03ec-11e6-81fc-c2d95f685ffb.png)

how can i solve this problem,thanks any way.

**Comment by jrivard** [comment]
You need to designate a group that has members in it, and the members need
to be beneath the user context you set in the previous step.  There's not
much to it.  Look at the log files if your not seeing a match.

**Comment by azura-vergo** [comment]
@jrivard  first of all,thanks for you reply.
and ,i still can not make it.
could you give me a more specific examples?

**Comment by jrivard** [comment]
please ask for help on the pwm-general google group.

**Comment by madmouser1** [comment]
The MemberOf module must be present on your OpenLDAP server and the admin user/s be members of the group as defined in the DN.

**Comment by hydrian** [comment]
The OpenLDAP MemberOf overlay is not replication safe and is in the process of being deprecated. It is recommend to use dynlist or dyngroup as the memberOf replacement.
