### ISSUE TITLE
receiving error 5054:  Unable to check PWM current version

### ISSUE THREAD

**Issue by Mets2022** [pwm-project/pwm#653]
ERROR_UNREACHABLE_CLOUD_SERVICE (unable to reach version check service 'https://pwm-cloud.appspot.com/rest/pwm/current-version', error: http response error code: 500)

**Comment by Mets2022** [comment]
When accessing the above link separately, I get the following:  Server error, The server encountered an error and could not complete your request.

**Comment by jrivard** [comment]
The version of PWM that uses that URL is quite old and outdated.  You should consider upgrading to a current release.
