### ISSUE TITLE
Unexpected error while testing ldap test user and impossible to write the FQDN in LDAP URLs

### ISSUE THREAD

**Issue by cmontanes** [pwm-project/pwm#658]
Hi everyone,

When I perform "test ldap profile" I get the following output -->
GOOD- All configured LDAP servers are reachable
WARNING- Unexpected  error while testing ldap test user LDAP ⇨ LDAP Directories ⇨ default ⇨  Connection ⇨ LDAP Test User, error: error setting test user password:  password.pwm.error.PwmUnrecoverableException: 5015 ERROR_INTERNAL

-It gives me an error with a proxy user that I created for PWM (domain admin) and also with the "administrator" user in AD, so I think is not a permissions problem.

-On the other hand, although it appears that the DC is reachable, I cannot put the FQDN in LDAP URLs because our domain contains "_" (whitout quotes). I also tried to indicate it in the PwmConfiguration.xml file but after the web does not start.

Can someone help me with these two doubts?

Thanks in advance.

**Comment by jrivard** [comment]
please post trace level log output

**Comment by jrivard** [comment]
Closing since no answer.
