### ISSUE TITLE
Error 5001 when users are member of group "protected users"

### ISSUE THREAD

**Issue by mellymello** [pwm-project/pwm#659]
**Describe the bug**
Users member of the group "protected users" in the AD cannot login and receive an error claiming the username or password is wrong. The logs doesn't have the login attempt or any errors. The only thing displayed is the popup with the title error 5001 and the description.    

It's a Windows recommendation to add Admin and such accounts with high privileges into this group

**To Reproduce**
Add user to the group "protected user" in AD and try to login

**Screenshots**
![image](https://user-images.githubusercontent.com/6839089/167588474-f3a0775d-092c-4f39-bfea-8ce6f76d21ac.png)

**Comment by jrivard** [comment]
Set log levels to trace and ask for help on the pwm-general list.
