### ISSUE TITLE
error 5017

### ISSUE THREAD

**Issue by rudineicorrea** [pwm-project/pwm#661]
I have an error after installation that no one can log in. the following error is displayed:

5017 ERROR_DIRECTORY_UNAVAILABLE (unexpected error during ldap search (profile=default), error: 5017 ERROR_DIRECTORY_UNAVAILABLE (unable to reach any configured server, maximum retries exceeded))

Is this error already known?

**Comment by jrivard** [comment]
This is not a defect, please ask for help on the pwm-general group.
