### ISSUE TITLE
configuration interface goes frozen after clicking "Test Email Settings". 

### ISSUE THREAD

**Issue by geekmichael** [pwm-project/pwm#665]
The configuration interface goes frozen after clicking "Test Email Settings". 

**To Reproduce**
1. Go to 'Settings' > Email > Email Servers > default
2. Update SMTP server settings, in my case, Office 365 settings (smtp.office365.com, StartTLS, 587)
3. Also fill the username with my email address(Office 365 account) and password
4. Click "Test Email Settings"
5. A loading box will be displayed util the session expired.
6. An Uncaught TypeError in Developer Tools

**Expected behavior**
A test message should be sent out with no hassle. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6998328/175819471-e94573f6-de10-463d-8920-174bf70bd9a8.png)

**Desktop:**
 - OS: Windows 10 21H1
 - Browser Google chrome

**Server**
 - OS: Ubuntu 22.02
 - Tomcat 9.0.58
 - PWM: 2.0.1
 - openjdk version "11.0.14.1" 2022-02-08

**Comment by jrivard** [comment]
PWM Version?

Logs?
