### ISSUE TITLE
Latest build: Force Update Profile not enforced

### ISSUE THREAD

**Issue by linux390** [pwm-project/pwm#67]
In the latest build, Force Update Profile seems to have no effect - the settings to configure an LDAP query to trigger this was removed in the Dec 21 2015 update.

**Comment by gadshaked** [comment]
Hi,
Any Update on this issue?
Gad

**Comment by jrivard** [comment]
Fixed in commit 9f059e62e8ebb29cb418fd0d3b554504d1176740

**Comment by waa8288** [comment]
Hi There,
When using "New User Registration" module to create new account, The account is created on top LDAP tree level. I want the account to be created under, let say under group,  "OU=TEST". How can I achieve that in PWM using the module.
