### ISSUE TITLE
Edit Configuration, form uses GET should use POST

### ISSUE THREAD

**Issue by BloodyIron** [pwm-project/pwm#679]
I'm setting PWM up initially, and it threw an error when going to the configuration editor (but this wasn't actually a blocker), and I noticed the form uses GET instead of POST for the method. As a result, my password was in CLEAR TEXT from the form on that error page.

This is a bad security practice, so we really need forms on PWM to use POST instead of GET. Can we please have this change added to some sort of milestone?

**Comment by BloodyIron** [comment]
2.0.0-SNAPSHOT

I don't remember which form it was, but I mean this should be pretty easy to search all forms in the code for which are using GET and not POST.

I'm using that version of PWM as it is what is used in fjudith/pwm:latest (dockerhub image), and other images are lacking things I need from that image (I don't remember which this very moment, but I've already done comparisons between image options).

**Comment by jrivard** [comment]
If your using:  https://hub.docker.com/r/fjudith/pwm then that looks like PWM v1.9.1, which is very outdated.   I'm also baffled why someone would use a 3rd party image for security software, but good luck.    If there is some reason you can't use the official docker image  you should open an issue for that...

Closing as this isn't against current version and you haven't given any specifics to address.

**Comment by BloodyIron** [comment]
Because that image includes a plugin that I need, the official one does not, and I don't want to fork the official one just for inserting the database plugin. I had already looked at the official one, the missing plugin (and I believe a few other things I can't recall right now) was really a big enough deal for me to use this other image.

Also, if you _actually_ read the tags section (and not the seemingly slightly out of date main page) you will see there is a 2.0.0-SNAPSHOT docker image tag, which... is why I said I'm using 2.0.0-SNAPSHOT and not v1.9.1.

And how does any of this invalidate the original point of me seeing forms using GET instead of POST method?

Again, I do not remember which form was using GET instead of POST method, do you want blood from a stone here? Surely it's trivial to tell which forms in the code are using GET instead of POST method... why do I have to explicitly remember which form(s) are relevant for this to actually be taken seriously?

**Comment by jrivard** [comment]
Sorry, I didn't see the newer image, I don't really understand dockerhub that well.  I did my best to read the Dockerfile.   However, 2.0.0-SNAPSHOT is still very out of date, v2.0.4 is the current version and includes important security updates.  Running a snapshot release is definitely not recommended.

You can upload a database plugin into the configuration, and it is stored inside the configuration file.  There should be no need to have the database plugin be part of the image.

There are hundreds of forms and entry points in PWM, many of which use GET for legitimate reasons, so unless you indicate which servlet or processAction your seeing an issue with I can't find what your referring to.  It is not trivial to examine them all.
