### ISSUE TITLE
Documentation Improvement: Database option listed as alternative to Schema Extension

### ISSUE THREAD

**Issue by BloodyIron** [pwm-project/pwm#680]
On this page : https://github.com/pwm-project/pwm/wiki/General-Directory-Setup

It lists that Schema changes are required, but this is not correct, as use of an External Database for such records is a functional alternative.

Discovering this information was a lot of work, and I think it would be prudent for the documentation to be updated to actually talk about the Database alternative options.

The documentation in general seems to be rather in need of loving, since it talks also about very old versions of Ubuntu.

**Comment by jrivard** [comment]
It's a wiki..... just edit it!   Looking forward to your updates.

**Comment by BloodyIron** [comment]
Sure, except I didn't write the tool and I don't know all the content to put to paper. I'm plenty capable of writing documentation... for things I already know... hence asking for the developers to expand on this, please.
