### ISSUE TITLE
Recaptcha pop-up disappears and there is no way to let it appear again

### ISSUE THREAD

**Issue by danifran** [pwm-project/pwm#687]
**Describe the bug**
When recaptcha determines that a user needs to prove that is not a robot, if the user click outside the recaptcha pop-up in the page, the pop-up disappears and there is no visual hint (and no ways) to let it appear again. The user remains locked in the page until the timeout expires or the user reload the page againt

**To Reproduce**
1. Enable recaptcha for forgot password page in silent mode
2. Go to the forgot password page and type a username
3. Repeat the step 2 a lot of times, until Google chooses to show you the recaptcha pop-up
4. Click outside the recaptcha pop-up. the pop-up will disappear.
5. You remain stuck on the page

**Expected behavior**
Clicking outside the window should not let the recaptcha disappear, or at least a new button should be present to let it pop-up again

**Screenshots**
<img width="441" alt="image" src="https://user-images.githubusercontent.com/34513818/216553581-2830d73c-2f67-4268-b55a-13692ed02efd.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 109

**Comment by jrivard** [comment]
PWM Version?

**Comment by danifran** [comment]
2.0.3

**Comment by jrivard** [comment]
Please re-open if this is still an issue with 2.0.6.  Be adviced re-captcha will only work properly if PWM is accessed via an https (not http) url.
