### ISSUE TITLE
User profile update - blank fields

### ISSUE THREAD

**Issue by fabioandreteles** [pwm-project/pwm#69]
When trying to update a user profile, if there is no information in the fields (in my case otherMailbox and mobile), the user can use the update button and the program will try to send an email and sms to a blank number. 

Looked on PWM_UPDATE.validateForm funtion, and if possible it would be good not to send if blank or make user fill all fields.

**Comment by jrivard** [comment]
fixed in commit 9f059e62e8ebb29cb418fd0d3b554504d1176740.  Form was missing 'required' option.
