### ISSUE TITLE
No password meets the password policy

### ISSUE THREAD

**Issue by mtsadminhki** [pwm-project/pwm#693]
We are about testing version 2.0.5
If I try to change a password no password meets the policy. 
It always says, if I have numbers in it:
![grafik](https://user-images.githubusercontent.com/122776494/218999358-6b9a3f8b-7e6f-4f70-80da-e0a6cc31dc42.png)

In our old pwm Version 1.9.2 the same password with the same policy works.

![grafik](https://user-images.githubusercontent.com/122776494/218999232-bcc2779d-bbac-41f4-bb7e-7f3c79503d8d.png)

We use NetIQeDirectory with NMAS Respones enabled.

**Comment by aydnyldrm** [comment]
Same problem.

**Comment by jrivard** [comment]
At some point in time, eDirectory added additional polices to NMAS.  I can't remember the speciifics, but it might be "Allow non-alphanumeric characters in the password." based on the error your getting.  Be sure this is enabled in your eDirectory policy.  You can get a better view of the effective password policy in Admin -> User Debug and see how the actual effective policy is calculated, the end-user display is not exhaustive.

**Comment by mtsadminhki** [comment]
Sorry for bothering again. But I had check the NMAS  password policy with the user debug tool for the same user once with PWM Version 1.8 and once with PWM >2.0 (same PwmConfiguration.xml) and the difference is that the attribut    "AllowNonAlpha" is in Version 1.8. readable and shown as "true"  (like in NMAS defined) and with the programm > 2.0 the attribute is not found (n/a) for the same user with the same password policy in eDirectory. 
Because of this we could not use our Password policy from eDirectory with version >2.0.
Would it be possible to check this ?

Both json from user debug are in the attachment.

Regards
Andrea Matthies

-- 
AG ITLeibniz Institut für Naturstoff-Forschung und InfektionsbiologieHans-Knöll-Institut Beutenbergstr. 11a07745 Jena / GermanyTelefon: 036415321021
