### ISSUE TITLE
ForgottenPassword behaves differently causing FATAL for uids containing a specific number

### ISSUE THREAD

**Issue by sandroiv** [pwm-project/pwm#696]
**Describe the bug**
When passwordRetryCount is not present AND the uid/userIdentity contains the number 3 we end up with FATAL error in forgotten password module. 

**To Reproduce**
1. Create an account/uid in IPA ( Runs DS389 ) that contains the number 3. E.G. test3_pwm
2. Try resetting password via forgotten password module of this user. 
4. See error ERROR_DIRECTORY_UNAVAILABLE

**Expected behavior**
The behavior should be the same for any other account not containing the number 3, which is throwing ERROR_UNLOCK_FAILURE and continue without FATAL. 
Note: The error happens since passwordRetryCount does not exist in IPA, which is OK as long as we dont end in FATAL.

ERROR, forgottenpw.ForgottenPasswordServlet, {Kgo96} 5046 ERROR_UNLOCK_FAILURE (unable to unlock user ...... error: javax.naming.NoPermissionException: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry ...

**Logs showing the problem**
 TRACE, forgottenpw.ForgottenPasswordServlet, {DAMdd} all recovery checks passed, proceeding to configured recovery action [server]
 DEBUG, password.PasswordUtility, {DAMdd} testing password policy profile 'default' [server]
 DEBUG, permission.UserPermissionUtility, {DAMdd} user uid=test3_pwm,server (default) is a match for permission 'UserPermission(type=ldapAllUsers, ldapProfileID=all, ldapQuery=null, ldapBase=null)' (0ms) [server]
 TRACE, password.PasswordUtility, {DAMdd} readPasswordPolicyForUser completed (0ms) [server]
 TRACE, ldap.UserInfoReader, {DAMdd} beginning password status check process for uid=test3_pwm,server [server]
 TRACE, ldap.UserInfoReader, {DAMdd} password for uid=test3_pwm,server does not appear to be expired [server]
 DEBUG, ldap.UserInfoReader, {DAMdd} completed user password status check for uid=test3_pwm,server PasswordStatus.PasswordStatusBuilder(expired=false, preExpired=false, violatesPolicy=false, warnPeriod=false) (1ms) [server]
 TRACE, provider.JNDIProviderImpl, error during write of attribute 'passwordRetryCount', error: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.]
<Here is where the different behavior happens , we should have an ERROR and continue >
 WARN , provider.FailOverWrapper, unable to reach ldap server ldaps://server:636, last error: javax.naming.NoPermissionException: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.
 TRACE, provider.JNDIProviderImpl, bind successful as uid=some-proxy-user,server (45ms)
 TRACE, provider.JNDIProviderImpl, error during write of attribute 'passwordRetryCount', error: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.
 WARN , provider.FailOverWrapper, unable to reach ldap server ldaps://server:636, last error: javax.naming.NoPermissionException: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.
 TRACE, provider.JNDIProviderImpl, bind successful as uid=some-proxy-user,server (45ms)
 TRACE, provider.JNDIProviderImpl, error during write of attribute 'passwordRetryCount', error: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.
 WARN , provider.FailOverWrapper, unable to reach ldap server ldaps://server:636, last error: javax.naming.NoPermissionException: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.
 TRACE, provider.JNDIProviderImpl, bind successful as uid=some-proxy-user,server (45ms)
 TRACE, provider.JNDIProviderImpl, error during write of attribute 'passwordRetryCount', error: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.
 WARN , provider.FailOverWrapper, unable to reach ldap server ldaps://server:636, last error: javax.naming.NoPermissionException: [LDAP: error code 50 - Insufficient 'write' privilege to the 'passwordRetryCount' attribute of entry 'uid=test3_pwm,server'.
 TRACE, provider.JNDIProviderImpl, bind successful as uid=some-proxy-user,server (44ms)
 FATAL, servlet.AbstractPwmServlet, {DAMdd} 5017 ERROR_DIRECTORY_UNAVAILABLE (unable to contact ldap directory: unable to reach any configured server, maximum retries exceeded) [server]
 ERROR, http.PwmResponse, {DAMdd} 5017 ERROR_DIRECTORY_UNAVAILABLE (unable to contact ldap directory: unable to reach any configured server, maximum retries exceeded) [server]

**Comment by jrivard** [comment]
So, looking at the this doc from DS389:he password

https://www.port389.org/docs/389ds/howto/howto-passwordreset.html

It says passwordRetryCount needs to be removed,  The ldap chai code for handling parssword reset also "unlocks" the password using the method here:

https://github.com/ldapchai/ldapchai/blob/ad898966c0d1af36f9ab081f53fd3dcadb881458/src/main/java/com/novell/ldapchai/impl/directoryServer389/entry/DirectoryServer389User.java#L86C20-L86C20

It seems from the error there is permission issue where the proxy user doesnt have writes to write to the passwordRetryCount attribute.   I'm not sure how the uid value is a factor here.

Please check your proxy user has write permission users passwordRetryCount attribute for users, and re-open if this is still an issue.

**Comment by sandroiv** [comment]
Hi Jason, 

Thank you for your update.

The permission error on passwordRetryCount happens because PWM is set to LDAP Vendor "OpenLDAP" and our backend is running IPA. We could try extending our schema in order to have this attribute available, but this error is not a big deal since it happens on every user password unlock and never impacted users / pwm service.

The real issue is the error ERROR_DIRECTORY_UNAVAILABLE  which happens only with accounts that contain the number 3. ( Yes, makes no sense but it is really this problem ).
