### ISSUE TITLE
Check password error?

### ISSUE THREAD

**Issue by cheekymonkat** [pwm-project/pwm#7]
Hi,

I've just updated to your latest build (2015-11-04T18:42:37Z-pwm-1.8.0-SNAPSHOT.war) - when changing password I get the error:

Request URL:https://myserver/password/public/rest/checkpassword?pwmFormID=5xpXzLra3sOni0yBG6YKp4L6lLJQpglo150f720b964u3fAb&preventCache=1447255221334
Request Method:POST
Status Code:415 Unsupported Media Type

Is this a defect or do I need to set something?  Thanks

**Comment by jrivard** [comment]
I don't see this using the 2015-11-09T20_48_57Z build.  The jersey library version has changed recently which would affect this.  try cleaning out your tomcat/work/* directory.
