### ISSUE TITLE
ChangePassword module to display both current and new password on same page

### ISSUE THREAD

**Issue by deejvince** [pwm-project/pwm#70]
Hi,
Can this be achieved?
(instead of 2 step process, when "Require Current Password during change" is set to true, we want to have just one page with both old and new passwords).
i suspect that requires edit to JSP.. can anyone help with that, or possibly make that a configuration option?

Thank you
DeeJVince

**Comment by jcombs-pointblue** [comment]
It can be done with some customization.  Contact me if your interested in contracting for the work.

Jerry Combs
jcombs@pointbluetech.com <mailto:jcombs@pointbluetech.com>
https://www.pointbluetech.com <https://www.pointbluetech.com/>

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
