### ISSUE TITLE
Error during admin group validation: 5015 ERROR_INTERNAL (unexpected error during ldap search (profile=default), error: 5015 ERROR_INTERNAL (ldap error during searchID=0, context=DC=xxxxx,DC=xx, error=javax.naming.PartialResultException: Unprocessed Continuation Reference(s)))

### ISSUE THREAD

**Issue by calibredj** [pwm-project/pwm#706]
Error Adding admin group. 

Error during admin group validation: 5015 ERROR_INTERNAL (unexpected error during ldap search (profile=default), error: 5015 ERROR_INTERNAL (ldap error during searchID=0, context=DC=domain,DC=com, error=javax.naming.PartialResultException: Unprocessed Continuation Reference(s)))

**Comment by jrivard** [comment]
This has been discussed many time on the google group discussion list.  Please search there.
