### ISSUE TITLE
Self-service Change Password never works

### ISSUE THREAD

**Issue by bonhamcm** [pwm-project/pwm#71]
When a user attempts to change their password after all checks have succeeded, the user interface always brings up the password change page again.

In ```ChangePasswordServlet.handleChangeRequest()```, the ```changePasswordBean.isAllChecksPassed()``` method is set to false by default, calling ```advancedToNextStage()```:

```
if (!changePasswordBean.isAllChecksPassed()) {
    this.advancedToNextStage(pwmRequest, changePasswordBean);
    return;
}
```

If no other checks fail, the user is always back to the change password page:

```
changePasswordBean.setAllChecksPassed(true);
pwmRequest.forwardToJsp(PwmConstants.JSP_URL.PASSWORD_CHANGE);
```

**Comment by ekakela** [comment]
Any estimates when next official release with fixes of this is coming?

**Comment by jrivard** [comment]
Please ask for help on the pwm-general list.   This is not a bug as posted here.  Most likely the user's password is expired after being changed in your directory.  Check the logs and if you still can't identify the cause post the relevant logs on the list.
