### ISSUE TITLE
Whats the best way to theme PWM?

### ISSUE THREAD

**Issue by jdeezie** [pwm-project/pwm#72]
I've made a bunch of changes to the display of a PWM instance using CSS but its still kinda hacky without making changes to the HTML output below.

I'm wondering what would you guys would suggest would be the best way to essentially theme PWM. My initial thought is to make edits to the JSPs but there is worry about impacts when updating to a newer release.

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
