### ISSUE TITLE
telemetry is enabled by default

### ISSUE THREAD

**Issue by klasen** [pwm-project/pwm#77]
The options
- Enable Version Checking
- Enable Anonymous Statistics Publishing

must default to off.

[Directive 95/46/EC](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX:31995L0046:en:HTML) requires prior user consent before such data is transmitted.

**Comment by jrivard** [comment]
telemetry is now disabled in trunk
