### ISSUE TITLE
formular text not changed after cheanging locale

### ISSUE THREAD

**Issue by meiko** [pwm-project/pwm#97]
Problem with 1.8.0-SNAPSHOT (22.11.2016)

After switching the locale from default to de, the text of forms remains german. 
I can see, that the german json is loaded (containing the matching text), but 
<img width="587" alt="screen shot 2016-11-25 at 23 23 43" src="https://cloud.githubusercontent.com/assets/481335/20636047/41c68a66-b366-11e6-8b05-2ce25f4ca37c.png">
the text in the ui is still english.

**Comment by FZachlod** [comment]
PWM does not contain a translation for each and every message. You have to modify the messages from the configuration editor or add additional localizations. If no message for the chosen language is found the default (English) message will be shown.
