### ISSUE TITLE
update profile: read only attributes not working correctly

### ISSUE THREAD

**Issue by FZachlod** [pwm-project/pwm#98]
current snapshot.

we tried to include read only attributes in the update profile dialogue (in this case "username")

when you try to update a user profile:

![2016-11-28 14_52_23-pwmadmin password self service](https://cloud.githubusercontent.com/assets/19568338/20671006/daae10f2-b57b-11e6-8b26-6dc350f50db8.png)

firstly the attribute is shown correctly:

![2016-11-28 14_54_25-pwmadmin password self service](https://cloud.githubusercontent.com/assets/19568338/20671038/f906521c-b57b-11e6-8f41-a2fe37f41e00.png)

after hitting "update":

![2016-11-28 14_59_33-lakb_kmustermann password self service](https://cloud.githubusercontent.com/assets/19568338/20671065/11bd2a10-b57c-11e6-9375-dce430f5c088.png)

the attribute is shown empty

If you hit back

![2016-11-28 15_00_37-lakb_kmustermann password self service](https://cloud.githubusercontent.com/assets/19568338/20671093/29b82dc2-b57c-11e6-96cf-2155a728cd66.png)

it still is empty untill the user logs out and logs back in again.

As soon as we make the attribute writable the dialogues work correctly

**Comment by jrivard** [comment]
fixed in current trunk
